/**
 * Public mock-interview question packs.
 *
 * This file intentionally uses a classic script global instead of ES modules so it
 * can be loaded directly with a <script> tag. The CommonJS export keeps the same
 * data available to local validation and test tooling.
 */
var MOCK_QUESTION_PACKS = [
  {
    id: "wecom-smart-sheet-pm",
    title: "企业微信智能表格 · 产品经理",
    description:
      "面向企业协作与智能表格产品经理岗位的公开模拟题库，重点考察产品判断、AI 方案、企业级治理与落地能力。请基于公开信息或脱敏案例作答；本题库不代表任何公司的官方招聘标准或产品路线。",
    competencies: [
      "经历迁移与产品理解",
      "用户问题与需求抽象",
      "企业产品与平台判断",
      "AI 产品设计与评测",
      "数据权限与安全治理",
      "跨团队推进与复盘",
    ],
    version: "2.0.0",
    interviewFlow: {
      15: [
        "wecom-introduction",
        "wecom-flagship-project",
        "wecom-positioning",
        "wecom-ai-feature",
      ],
      30: [
        "wecom-introduction",
        "wecom-flagship-project",
        "wecom-method-transfer",
        "wecom-positioning",
        "wecom-ai-feature",
      ],
      45: [
        "wecom-introduction",
        "wecom-flagship-project",
        "wecom-method-transfer",
        "wecom-demand-abstraction",
        "wecom-positioning",
        "wecom-ai-feature",
        "wecom-ai-value",
        "wecom-disagreement",
      ],
    },
    questions: [
      {
        id: "wecom-introduction",
        category: "开场",
        priority: 0,
        maxFollowUps: 0,
        evaluationProfile: "introduction",
        question: "先简单介绍一下自己吧。",
        keywords: ["经历主线", "当前方向", "代表项目", "核心能力"],
        signalGroups: {
          context: { label: "个人背景", keywords: ["硕士", "本科", "专业", "实习", "经历"], required: true },
          action: { label: "经历主线", keywords: ["负责", "参与", "产品", "分析", "项目"], required: true },
          judgment: { label: "能力定位", keywords: ["擅长", "优势", "能力", "关注", "主线"], required: true },
        },
        followUps: [],
        evaluationDimensions: [
          { name: "信息取舍", lookFor: "在一分钟内交代背景、代表经历和能力主线。" },
          { name: "个人定位", lookFor: "让面试官知道后续最值得追问什么。" },
          { name: "表达自然度", lookFor: "口语化表达，不逐条复述简历。" },
        ],
      },
      {
        id: "wecom-method-transfer",
        category: "项目深挖",
        priority: 1,
        question: "你刚才这个项目里，哪些事情原来主要靠人工或经验？后来是怎么把它做成产品能力的？",
        keywords: ["业务问题", "知识结构化", "规则抽象", "产品化", "可配置", "复用验证"],
        signalGroups: {
          problem: { label: "原始问题", keywords: ["信息分散", "人工成本", "标准不一", "协作低效"], required: true },
          context: { label: "用户与约束", keywords: ["使用角色", "业务场景", "原有流程", "约束"], required: true },
          action: { label: "产品化过程", keywords: ["梳理", "抽象", "结构化", "配置", "上线"], required: true },
          evidence: { label: "复用证据", keywords: ["覆盖范围", "使用反馈", "效率", "准确率", "持续使用"], required: true },
          judgment: { label: "抽象取舍", keywords: ["共性与个性", "产品边界", "优先级", "治理"], required: true },
          reflection: { label: "迭代复盘", keywords: ["问题", "迭代", "可迁移方法", "下一步"], required: false },
        },
        followUps: [
          { id: "wecom-method-transfer-f1", triggerLabel: "直接罗列功能，没有还原产品化前的问题", requires: ["problem", "context"], question: "为什么当时不能继续靠人工或者文档来解决？" },
          { id: "wecom-method-transfer-f2", triggerLabel: "只讲整理过程，没有说明抽象和取舍", requires: ["action", "judgment"], question: "这里面哪些做成了统一规则，哪些保留了业务差异？" },
          { id: "wecom-method-transfer-f3", triggerLabel: "把交付完成当作产品有效", requires: ["evidence", "reflection"], question: "你怎么确认它真的改善了原来的流程？" },
        ],
        evaluationDimensions: [
          { name: "问题还原", lookFor: "说明产品化前的用户、流程、成本与核心矛盾。" },
          { name: "抽象能力", lookFor: "能从具体需求中拆出稳定共性与可配置差异。" },
          { name: "产品闭环", lookFor: "完整说明结构设计、协作推进、上线使用与治理机制。" },
          { name: "结果可信度", lookFor: "用覆盖、效率、质量或持续使用证据验证复用价值。" },
        ],
      },
      {
        id: "wecom-positioning",
        category: "产品判断",
        priority: 1,
        question: "你怎么理解企业微信智能表格？它主要在解决什么问题？",
        keywords: ["结构化记录", "轻量业务应用", "协作执行", "多角色", "产品边界", "价值闭环"],
        signalGroups: {
          problem: { label: "核心任务", keywords: ["记录管理", "流程协同", "动作闭环"], required: true },
          context: { label: "用户与场景", keywords: ["搭建者", "一线执行者", "管理者"], required: true },
          action: { label: "产品机制", keywords: ["字段与视图", "权限", "自动化"], required: true },
          evidence: { label: "验证信号", keywords: ["首次闭环", "持续更新", "组织留存"], required: false },
          judgment: { label: "定位边界", keywords: ["适用范围", "不替代", "差异化假设"], required: true },
          reflection: { label: "不确定性", keywords: ["公开信息边界", "待验证假设", "反例"], required: false },
        },
        followUps: [
          { id: "wecom-positioning-f1", triggerLabel: "把产品等同于带 AI 的传统表格", requires: ["problem", "action"], question: "那它和 Excel、普通在线表格最大的区别是什么？" },
          { id: "wecom-positioning-f2", triggerLabel: "声称能替代所有专业系统", requires: ["judgment", "reflection"], question: "哪些事情你觉得它并不适合做？" },
          { id: "wecom-positioning-f3", triggerLabel: "只有概念，缺少多角色和验证方式", requires: ["context", "evidence"], question: "谁会最先用它？为什么会持续用下去？" },
        ],
        evaluationDimensions: [
          { name: "定位清晰度", lookFor: "用用户任务和工作流定义产品，不堆叠空泛标签。" },
          { name: "多角色视角", lookFor: "同时考虑配置、执行、管理与治理角色的价值和成本。" },
          { name: "边界判断", lookFor: "能区分灵活协作流程与重型专业系统。" },
          { name: "验证意识", lookFor: "用真实闭环与持续采用验证定位，而非只看建表量。" },
        ],
      },
      {
        id: "wecom-flagship-project",
        category: "项目深挖",
        priority: 1,
        question: "挑一个你做得最深入的项目讲讲。",
        keywords: ["问题定义", "个人贡献", "关键取舍", "协同交付", "结果证据", "复盘"],
        signalGroups: {
          problem: { label: "问题定义", keywords: ["目标用户", "核心痛点", "为什么值得做"], required: true },
          context: { label: "约束背景", keywords: ["旧方案", "资源约束", "成功标准"], required: true },
          action: { label: "个人行动", keywords: ["本人决策", "方案推进", "交付验收"], required: true },
          evidence: { label: "结果证据", keywords: ["口径说明", "用户行为", "可信结果"], required: true },
          judgment: { label: "关键取舍", keywords: ["备选方案", "优先级", "风险权衡"], required: true },
          reflection: { label: "复盘迁移", keywords: ["未达预期", "机制改进", "可迁移方法"], required: true },
        },
        followUps: [
          { id: "wecom-flagship-project-f1", triggerLabel: "罗列功能，没有收敛核心问题", requires: ["problem", "context"], question: "这个项目一开始为什么要做？最核心的问题是什么？" },
          { id: "wecom-flagship-project-f2", triggerLabel: "大量使用“我们”，个人边界不清", requires: ["action", "judgment"], question: "你在里面具体负责哪一部分？有哪个关键判断是你做的？" },
          { id: "wecom-flagship-project-f3", triggerLabel: "结果缺少口径或只报正向结论", requires: ["evidence", "reflection"], question: "最后怎么判断它做得好不好？有没有没达到预期的地方？" },
        ],
        evaluationDimensions: [
          { name: "结构表达", lookFor: "完整串联问题、约束、行动、结果和复盘。" },
          { name: "所有权边界", lookFor: "清楚区分个人贡献、团队成果与专业角色责任。" },
          { name: "决策质量", lookFor: "呈现真实备选方案、证据和取舍。" },
          { name: "结果可信度", lookFor: "解释指标口径和未知边界，不编造或夸大。" },
        ],
      },
      {
        id: "wecom-demand-abstraction",
        category: "用户与需求",
        priority: 1,
        question: "业务方只说‘想用表格把这件事管起来’，你会先问什么？",
        keywords: ["用户任务", "业务对象", "字段关系", "角色权限", "自动化", "验收标准"],
        signalGroups: {
          problem: { label: "需求本质", keywords: ["目标动作", "现有阻碍", "使用频率"], required: true },
          context: { label: "业务模型", keywords: ["对象关系", "角色", "状态流转"], required: true },
          action: { label: "方案映射", keywords: ["字段视图", "权限规则", "触发动作"], required: true },
          evidence: { label: "验收证据", keywords: ["任务样例", "异常状态", "完成指标"], required: true },
          judgment: { label: "抽象取舍", keywords: ["通用与定制", "一期边界", "维护成本"], required: true },
          reflection: { label: "迭代机制", keywords: ["反馈回流", "配置摩擦", "扩展条件"], required: false },
        },
        followUps: [
          { id: "wecom-demand-abstraction-f1", triggerLabel: "按用户原话直接堆功能", requires: ["problem", "context"], question: "谁在用？现在是怎么做的？最卡的是哪一步？" },
          { id: "wecom-demand-abstraction-f2", triggerLabel: "方案过度定制或过度通用", requires: ["action", "judgment"], question: "如果一期只能解决一个问题，你先做什么？" },
          { id: "wecom-demand-abstraction-f3", triggerLabel: "把搭建完成当作验收完成", requires: ["evidence", "reflection"], question: "上线后你怎么判断这个需求真的解决了？" },
        ],
        evaluationDimensions: [
          { name: "需求抽象", lookFor: "把口头诉求还原为业务对象、角色、状态和动作。" },
          { name: "方案完整性", lookFor: "覆盖数据结构、视图、权限、自动化与异常状态。" },
          { name: "平台取舍", lookFor: "平衡通用能力、场景模板和个性配置。" },
          { name: "任务验收", lookFor: "以真实任务改善而非页面交付作为成功标准。" },
        ],
      },
      {
        id: "wecom-competitive-differentiation",
        category: "产品判断",
        priority: 2,
        question: "飞书多维表格、钉钉 AI 表格已经比较成熟了，你觉得企微的机会在哪？",
        keywords: ["目标场景", "原生协作", "迁移成本", "能力门槛", "竞争假设", "验证指标"],
        signalGroups: {
          problem: { label: "竞争问题", keywords: ["用户为何切换", "替代成本", "同质化"], required: true },
          context: { label: "竞争语境", keywords: ["用户存量工具", "组织协作", "生态约束"], required: true },
          action: { label: "验证方案", keywords: ["同场景对比", "局部迁移", "小范围试点"], required: true },
          evidence: { label: "差异证据", keywords: ["配置步骤", "闭环耗时", "可靠性"], required: true },
          judgment: { label: "竞争判断", keywords: ["基础门槛", "独特资产", "成立条件"], required: true },
          reflection: { label: "反例边界", keywords: ["优势不成立", "并存策略", "不强迫迁移"], required: true },
        },
        followUps: [
          { id: "wecom-competitive-differentiation-f1", triggerLabel: "只比较功能数量", requires: ["problem", "judgment"], question: "如果功能都差不多，用户为什么要换？" },
          { id: "wecom-competitive-differentiation-f2", triggerLabel: "把入口或关系网络直接当作壁垒", requires: ["evidence", "reflection"], question: "你怎么证明企微里的关系链真的能带来优势？" },
          { id: "wecom-competitive-differentiation-f3", triggerLabel: "默认用户会整体迁移", requires: ["context", "action"], question: "如果用户不愿意放弃现在的工具，你会怎么办？" },
        ],
        evaluationDimensions: [
          { name: "竞争框架", lookFor: "比较场景、链路与结果，不做功能清单或品牌站队。" },
          { name: "假设意识", lookFor: "把潜在优势视为需验证假设，并说明成立条件。" },
          { name: "用户成本", lookFor: "考虑学习、迁移、集成和组织切换成本。" },
          { name: "反证能力", lookFor: "能明确何种证据会否定原判断。" },
        ],
      },
      {
        id: "wecom-ai-feature",
        category: "AI 产品设计",
        priority: 1,
        question: "如果让你给智能表格加一个 AI 能力，你会先做什么？",
        keywords: ["窄场景", "用户任务", "结构化配置", "人机协作", "风险控制", "实验验证"],
        signalGroups: {
          problem: { label: "场景痛点", keywords: ["高频任务", "人工成本", "结果明确"], required: true },
          context: { label: "用户流程", keywords: ["输入来源", "使用角色", "下游动作"], required: true },
          action: { label: "产品方案", keywords: ["信息补齐", "生成预览", "确认执行"], required: true },
          evidence: { label: "实验证据", keywords: ["完成率", "耗时", "修改率"], required: true },
          judgment: { label: "MVP 取舍", keywords: ["一期范围", "不用 AI 的部分", "平台适配"], required: true },
          reflection: { label: "风险边界", keywords: ["错误后果", "人工兜底", "回滚"], required: true },
        },
        followUps: [
          { id: "wecom-ai-feature-f1", triggerLabel: "设计成泛化聊天框，缺少具体任务", requires: ["problem", "context"], question: "这个需求是谁在什么环节遇到的？" },
          { id: "wecom-ai-feature-f2", triggerLabel: "一期范围过大或没有方案取舍", requires: ["action", "judgment"], question: "一期只能做得很小，你会保留什么？" },
          { id: "wecom-ai-feature-f3", triggerLabel: "默认 AI 可直接写入或外发", requires: ["evidence", "reflection"], question: "AI 做错了会怎样？哪些动作不能让它直接做？" },
        ],
        evaluationDimensions: [
          { name: "场景选择", lookFor: "选择高频、结果可判定且适合结构化数据的任务。" },
          { name: "方案闭环", lookFor: "覆盖输入、处理、预览、执行、异常和结果回填。" },
          { name: "MVP 取舍", lookFor: "明确一期边界和非 AI 更合适的部分。" },
          { name: "安全可控", lookFor: "按风险设置确认、审计、人工兜底与回滚。" },
          { name: "验证设计", lookFor: "比较原流程与新流程的任务结果，而非只看调用。" },
        ],
      },
      {
        id: "wecom-ai-value",
        category: "指标与实验",
        priority: 1,
        question: "这个 AI 功能上线以后，你会看哪些数据判断它有没有用？",
        keywords: ["真实激活", "输出质量", "下游动作", "持续使用", "业务结果", "护栏指标"],
        signalGroups: {
          problem: { label: "价值问题", keywords: ["目标任务", "原流程基线", "用户成本"], required: true },
          context: { label: "任务周期", keywords: ["使用频率", "角色差异", "样本条件"], required: true },
          action: { label: "验证设计", keywords: ["对照", "分阶段开放", "质量抽检"], required: true },
          evidence: { label: "指标链条", keywords: ["完成率", "修改率", "下游动作", "留存"], required: true },
          judgment: { label: "因果判断", keywords: ["虚荣指标", "选择偏差", "任务归因"], required: true },
          reflection: { label: "护栏复盘", keywords: ["严重错误", "延迟成本", "停止阈值"], required: true },
        },
        followUps: [
          { id: "wecom-ai-value-f1", triggerLabel: "只看调用量、人数或采纳率", requires: ["problem", "evidence"], question: "调用量很高，就一定说明有价值吗？" },
          { id: "wecom-ai-value-f2", triggerLabel: "忽略任务周期或用户差异", requires: ["context", "judgment"], question: "如果这个任务本来就很低频，你怎么衡量？" },
          { id: "wecom-ai-value-f3", triggerLabel: "没有因果验证与风险护栏", requires: ["action", "reflection"], question: "你怎么排除只是新鲜感或者用户本来就更积极？" },
        ],
        evaluationDimensions: [
          { name: "价值链条", lookFor: "从激活、质量、下游动作到持续结果逐层验证。" },
          { name: "指标质量", lookFor: "组合任务指标与护栏指标，不依赖单一虚荣指标。" },
          { name: "因果意识", lookFor: "识别样本偏差，并采用合理对照或阶段比较。" },
          { name: "周期匹配", lookFor: "指标周期符合任务真实发生频率。" },
        ],
      },
      {
        id: "wecom-cold-start",
        category: "增长与采用",
        priority: 1,
        question: "这类企业产品如果从零开始，你会先从什么场景切？",
        keywords: ["窄场景", "种子用户", "首次闭环", "高接触验证", "产品化沉淀", "组织留存"],
        signalGroups: {
          problem: { label: "切入痛点", keywords: ["高频流程", "明确损失", "角色完整"], required: true },
          context: { label: "种子条件", keywords: ["数据可用", "共创意愿", "决策链"], required: true },
          action: { label: "启动路径", keywords: ["陪跑", "模板", "迁移与引导"], required: true },
          evidence: { label: "采用证据", keywords: ["首次价值", "一线更新", "组织留存"], required: true },
          judgment: { label: "规模化判断", keywords: ["共性障碍", "人工与产品", "复制条件"], required: true },
          reflection: { label: "失活诊断", keywords: ["旧流程并存", "配置负担", "激励错位"], required: false },
        },
        followUps: [
          { id: "wecom-cold-start-f1", triggerLabel: "从万能空表或广泛获客开始", requires: ["problem", "context"], question: "第一批用户你会找谁？" },
          { id: "wecom-cold-start-f2", triggerLabel: "把开通、建表或导入当作激活", requires: ["action", "evidence"], question: "用户做到哪一步，才算真的用起来了？" },
          { id: "wecom-cold-start-f3", triggerLabel: "长期依赖人工实施，缺少规模化路径", requires: ["judgment", "reflection"], question: "前期可以靠人陪跑，后面怎么把它规模化？" },
        ],
        evaluationDimensions: [
          { name: "切入策略", lookFor: "从痛点强、角色清楚且能闭环的窄流程切入。" },
          { name: "激活定义", lookFor: "以真实数据进入、责任行动与结果回填定义首次价值。" },
          { name: "组织采用", lookFor: "关注不同角色行为和旧流程是否真正迁移。" },
          { name: "规模化路径", lookFor: "将高接触验证中的共性障碍沉淀为产品能力。" },
        ],
      },
      {
        id: "wecom-prioritization",
        category: "产品规划",
        priority: 1,
        question: "现在权限问题、导入失败、AI 新需求和界面优化同时来了，你怎么排？",
        keywords: ["信任底线", "用户价值", "影响范围", "证据置信度", "成本风险", "复盘"],
        signalGroups: {
          problem: { label: "问题分层", keywords: ["安全风险", "核心阻塞", "体验改善"], required: true },
          context: { label: "影响语境", keywords: ["用户范围", "发生频次", "商业与合规"], required: true },
          action: { label: "决策过程", keywords: ["证据收集", "技术评估", "资源编排"], required: true },
          evidence: { label: "排序证据", keywords: ["故障数据", "用户行为", "客户反馈"], required: true },
          judgment: { label: "优先级原则", keywords: ["底线优先", "价值风险", "战略一致"], required: true },
          reflection: { label: "结果复盘", keywords: ["复发率", "任务改善", "假设更新"], required: false },
        },
        followUps: [
          { id: "wecom-prioritization-f1", triggerLabel: "机械套用评分公式", requires: ["problem", "judgment"], question: "你先讲原则，再讲这四个具体会怎么排。" },
          { id: "wecom-prioritization-f2", triggerLabel: "只依赖单一声音或职位高低", requires: ["context", "evidence"], question: "如果老板最关心的和你的判断不一样，你怎么沟通？" },
          { id: "wecom-prioritization-f3", triggerLabel: "没有落地和复盘机制", requires: ["action", "reflection"], question: "排完以后，你怎么知道当时的判断是对的？" },
        ],
        evaluationDimensions: [
          { name: "分层原则", lookFor: "先守权限、安全、数据正确和稳定性底线。" },
          { name: "证据质量", lookFor: "综合行为、反馈、故障、商业与技术证据。" },
          { name: "取舍沟通", lookFor: "用共同目标、备选方案和代价说明优先级。" },
          { name: "复盘能力", lookFor: "上线后检验任务改善、风险变化与原假设。" },
        ],
      },
      {
        id: "wecom-ai-permissions",
        category: "安全与治理",
        priority: 1,
        question: "如果 AI 能读表、改表，甚至自动发消息，你最担心什么？",
        keywords: ["最小权限", "取数裁剪", "动作校验", "敏感数据", "审计", "回滚"],
        signalGroups: {
          problem: { label: "风险识别", keywords: ["越权读取", "越权推断", "错误执行"], required: true },
          context: { label: "权限语境", keywords: ["用户权限", "任务授权", "数据敏感级别"], required: true },
          action: { label: "控制机制", keywords: ["读取前裁剪", "二次校验", "预览确认"], required: true },
          evidence: { label: "治理证据", keywords: ["授权记录", "执行日志", "安全测试"], required: true },
          judgment: { label: "风险分级", keywords: ["可逆操作", "高风险动作", "人工确认"], required: true },
          reflection: { label: "对抗与恢复", keywords: ["恶意指令", "异常检测", "撤销回滚"], required: true },
        },
        followUps: [
          { id: "wecom-ai-permissions-f1", triggerLabel: "只说沿用用户权限，没有说明取数阶段", requires: ["context", "action"], question: "用户只能看一部分数据时，AI 最后能总结到什么程度？" },
          { id: "wecom-ai-permissions-f2", triggerLabel: "所有动作一律自动或一律确认", requires: ["judgment", "evidence"], question: "哪些动作可以自动做，哪些必须让人确认？" },
          { id: "wecom-ai-permissions-f3", triggerLabel: "忽略输入攻击、审计或恢复", requires: ["problem", "reflection"], question: "如果它批量做错了，怎么发现、怎么撤回？" },
        ],
        evaluationDimensions: [
          { name: "权限模型", lookFor: "AI 可见范围是用户权限与任务授权的交集，且取数前裁剪。" },
          { name: "动作安全", lookFor: "写入、外发和权限变更前重新校验并按风险确认。" },
          { name: "数据治理", lookFor: "考虑敏感级别、跨表聚合和间接推断风险。" },
          { name: "可审计恢复", lookFor: "保留授权、来源和执行日志，并具备撤销或回滚路径。" },
        ],
      },
      {
        id: "wecom-data-migration",
        category: "企业产品基础",
        priority: 2,
        question: "用户历史数据很乱，权限也不一致，你会怎么设计迁移？",
        keywords: ["数据盘点", "字段映射", "质量校验", "权限继承", "试迁移", "回退"],
        signalGroups: {
          problem: { label: "迁移风险", keywords: ["数据丢失", "口径冲突", "业务中断"], required: true },
          context: { label: "数据语境", keywords: ["来源类型", "数据规模", "角色权限"], required: true },
          action: { label: "迁移方案", keywords: ["字段映射", "预检查", "分批迁移"], required: true },
          evidence: { label: "验收证据", keywords: ["抽样核对", "差异报告", "业务验收"], required: true },
          judgment: { label: "取舍策略", keywords: ["自动与人工", "阻断条件", "兼容范围"], required: true },
          reflection: { label: "恢复与治理", keywords: ["回退", "持续同步", "数据责任人"], required: true },
        },
        followUps: [
          { id: "wecom-data-migration-f1", triggerLabel: "只描述上传文件，没有数据盘点", requires: ["problem", "context"], question: "迁移前你最先盘什么？" },
          { id: "wecom-data-migration-f2", triggerLabel: "假设字段可以自动一一对应", requires: ["action", "judgment"], question: "哪些能自动处理，哪些必须让客户确认？" },
          { id: "wecom-data-migration-f3", triggerLabel: "没有验收、失败恢复和并存计划", requires: ["evidence", "reflection"], question: "如果迁移中途失败了，怎么保证业务不受影响？" },
        ],
        evaluationDimensions: [
          { name: "风险完整性", lookFor: "识别数据、口径、权限、依赖与业务连续性风险。" },
          { name: "迁移流程", lookFor: "包含预检查、映射、试迁移、校验、切换与回退。" },
          { name: "人机分工", lookFor: "自动处理确定性规则，将歧义与高风险项交给责任人。" },
          { name: "业务验收", lookFor: "不仅检查行数，还验证关键任务与权限结果。" },
        ],
      },
      {
        id: "wecom-ai-evaluation",
        category: "AI 产品设计",
        priority: 1,
        question: "一个 AI 功能上线前，你会怎么判断它够不够好？",
        keywords: ["任务分类", "评测集", "业务预期", "过程证据", "人工复核", "回归测试"],
        signalGroups: {
          problem: { label: "质量目标", keywords: ["任务成功", "严重错误", "用户影响"], required: true },
          context: { label: "样本结构", keywords: ["典型任务", "边界样本", "风险分层"], required: true },
          action: { label: "评测闭环", keywords: ["离线评测", "线上反馈", "归因修复", "回归"], required: true },
          evidence: { label: "可核验信号", keywords: ["预期结果", "可观察日志", "人工抽检"], required: true },
          judgment: { label: "评判边界", keywords: ["多种合理答案", "人机分工", "发布门槛"], required: true },
          reflection: { label: "评测治理", keywords: ["样本漂移", "评审偏差", "版本追踪"], required: true },
        },
        followUps: [
          { id: "wecom-ai-evaluation-f1", triggerLabel: "只说准备问题和标准答案", requires: ["problem", "context"], question: "除了用户问题，一条评测样本里还要有什么？" },
          { id: "wecom-ai-evaluation-f2", triggerLabel: "把自动打分当作最终裁判", requires: ["evidence", "judgment"], question: "自动评测和人工判断冲突了，听谁的？" },
          { id: "wecom-ai-evaluation-f3", triggerLabel: "评测止于跑分，没有回流迭代", requires: ["action", "reflection"], question: "发现 Bad Case 以后，怎么保证不是只修这一条？" },
        ],
        evaluationDimensions: [
          { name: "评测设计", lookFor: "按任务与风险分层，定义可核验预期和边界样本。" },
          { name: "证据质量", lookFor: "结合最终结果、可观察执行日志与人工抽检，不索取私有思维过程。" },
          { name: "闭环能力", lookFor: "串联发现、归因、修复、回归和版本治理。" },
          { name: "评判边界", lookFor: "识别多解、评审偏差与高风险人工复核需求。" },
        ],
      },
      {
        id: "wecom-bad-case",
        category: "AI 产品设计",
        priority: 2,
        question: "讲一个你印象比较深的 Bad Case。你们最后是怎么定位的？",
        keywords: ["预期与实际", "可观察证据", "根因分层", "责任边界", "泛化修复", "回归"],
        signalGroups: {
          problem: { label: "失败定义", keywords: ["用户任务", "预期结果", "实际表现"], required: true },
          context: { label: "发生条件", keywords: ["输入特征", "能力版本", "影响范围"], required: true },
          action: { label: "定位修复", keywords: ["核验预期", "分层归因", "推动责任人"], required: true },
          evidence: { label: "诊断证据", keywords: ["执行日志", "相邻样本", "回归结果"], required: true },
          judgment: { label: "根因判断", keywords: ["知识问题", "产品规则", "能力边界"], required: true },
          reflection: { label: "泛化学习", keywords: ["机制修复", "防止补丁", "监控更新"], required: true },
        },
        followUps: [
          { id: "wecom-bad-case-f1", triggerLabel: "只描述错误结果，缺少完整发生条件", requires: ["problem", "context"], question: "当时预期是什么，实际错在了哪里？" },
          { id: "wecom-bad-case-f2", triggerLabel: "直接断言模型错误，没有核验预期与证据", requires: ["evidence", "judgment"], question: "你怎么确定是系统的问题，不是评测标准本身有问题？" },
          { id: "wecom-bad-case-f3", triggerLabel: "修复只针对单条输入打补丁", requires: ["action", "reflection"], question: "修完以后，你们怎么确认同类问题不会再出现？" },
        ],
        evaluationDimensions: [
          { name: "案例完整性", lookFor: "脱敏说明预期、实际、条件、影响与证据。" },
          { name: "根因分析", lookFor: "区分数据、知识、流程、产品规则和能力边界。" },
          { name: "责任边界", lookFor: "明确本人归因与推动动作，以及专业责任人的实现工作。" },
          { name: "泛化修复", lookFor: "覆盖相邻表达与场景，并执行完整回归。" },
        ],
      },
      {
        id: "wecom-cross-team-launch",
        category: "协作与推进",
        priority: 2,
        question: "讲一个你跨团队推进上线的项目。",
        keywords: ["共同目标", "责任人", "口径对齐", "里程碑", "范围取舍", "业务验收"],
        signalGroups: {
          problem: { label: "协作难题", keywords: ["目标冲突", "依赖阻塞", "决策缺口"], required: true },
          context: { label: "协作语境", keywords: ["参与角色", "时间资源", "约束条件"], required: true },
          action: { label: "推进动作", keywords: ["共同依据", "责任机制", "节点跟踪"], required: true },
          evidence: { label: "交付证据", keywords: ["验收样例", "风险清单", "上线结果"], required: true },
          judgment: { label: "冲突取舍", keywords: ["争议类型", "决策权", "备选方案"], required: true },
          reflection: { label: "协作复盘", keywords: ["机制不足", "后续改进", "责任边界"], required: true },
        },
        followUps: [
          { id: "wecom-cross-team-launch-f1", triggerLabel: "只说沟通和催进度", requires: ["problem", "action"], question: "这个项目最难推进的点是什么？你具体做了什么？" },
          { id: "wecom-cross-team-launch-f2", triggerLabel: "没有呈现真实冲突或决策过程", requires: ["context", "judgment"], question: "中间最大的分歧是什么？最后谁做的决定？" },
          { id: "wecom-cross-team-launch-f3", triggerLabel: "只强调按时上线，没有质量与复盘", requires: ["evidence", "reflection"], question: "如果当时确定会延期，你会怎么处理？" },
        ],
        evaluationDimensions: [
          { name: "协作结构化", lookFor: "把口头共识落成范围、责任、节点、样例和验收规则。" },
          { name: "冲突处理", lookFor: "区分争议性质，让合适的责任人做决策。" },
          { name: "项目取舍", lookFor: "能给出时间、范围和风险的明确备选方案。" },
          { name: "个人推动力", lookFor: "有本人识别阻塞、组织决策和跟踪关闭的动作。" },
        ],
      },
      {
        id: "wecom-failure-reflection",
        category: "行为与复盘",
        priority: 3,
        question: "讲一次你做错判断的经历。",
        keywords: ["本人判断", "实际影响", "根因", "机制改进", "预防措施", "迁移学习"],
        signalGroups: {
          problem: { label: "错误判断", keywords: ["本人责任", "错误假设", "关键遗漏"], required: true },
          context: { label: "影响语境", keywords: ["用户影响", "协作成本", "项目后果"], required: true },
          action: { label: "补救行动", keywords: ["及时纠偏", "影响控制", "责任沟通"], required: true },
          evidence: { label: "改进证据", keywords: ["规则变化", "流程变化", "后续验证"], required: true },
          judgment: { label: "根因认识", keywords: ["为何误判", "系统原因", "边界条件"], required: true },
          reflection: { label: "迁移学习", keywords: ["预防机制", "升级阈值", "新决策原则"], required: true },
        },
        followUps: [
          { id: "wecom-failure-reflection-f1", triggerLabel: "把问题归因于环境或他人", requires: ["problem", "judgment"], question: "当时哪个判断是你做的？为什么会判断错？" },
          { id: "wecom-failure-reflection-f2", triggerLabel: "没有说明实际影响和补救", requires: ["context", "action"], question: "造成了什么影响？你当时先做了什么？" },
          { id: "wecom-failure-reflection-f3", triggerLabel: "改进停留在更细心或多沟通", requires: ["evidence", "reflection"], question: "这件事之后，你具体改了什么做法？" },
        ],
        evaluationDimensions: [
          { name: "责任承担", lookFor: "明确本人错误，不甩锅也不替团队承担全部责任。" },
          { name: "影响具体性", lookFor: "说明真实影响，不用虚构数字放大故事。" },
          { name: "根因深度", lookFor: "从表面失误追到假设、机制或边界问题。" },
          { name: "机制改进", lookFor: "将教训转化为可执行、可验证的规则或流程。" },
        ],
      },
      {
        id: "wecom-disagreement",
        category: "行为与复盘",
        priority: 3,
        question: "讲一次你和业务、设计或者研发意见不一致的经历。",
        keywords: ["换位理解", "争议拆解", "证据收敛", "决策边界", "结果处理", "可修正性"],
        signalGroups: {
          problem: { label: "分歧核心", keywords: ["目标差异", "方案冲突", "资源矛盾"], required: true },
          context: { label: "双方立场", keywords: ["合理顾虑", "共同目标", "约束"], required: true },
          action: { label: "收敛行动", keywords: ["事实核对", "小范围验证", "备选方案"], required: true },
          evidence: { label: "决策证据", keywords: ["用户样例", "数据", "实验结果"], required: true },
          judgment: { label: "决策机制", keywords: ["争议类型", "最终责任人", "取舍理由"], required: true },
          reflection: { label: "结果复盘", keywords: ["判断修正", "相邻影响", "协作改进"], required: true },
        },
        followUps: [
          { id: "wecom-disagreement-f1", triggerLabel: "把对方描述为被说服的阻力", requires: ["problem", "context"], question: "对方当时最合理的顾虑是什么？" },
          { id: "wecom-disagreement-f2", triggerLabel: "只靠表达技巧或职位拍板", requires: ["action", "evidence"], question: "你们最后是靠什么把分歧收敛下来的？" },
          { id: "wecom-disagreement-f3", triggerLabel: "没有说明决策归属与纠错方式", requires: ["judgment", "reflection"], question: "如果后来证明你错了，你会怎么处理？" },
        ],
        evaluationDimensions: [
          { name: "换位理解", lookFor: "准确呈现不同角色的目标、约束和合理顾虑。" },
          { name: "争议拆解", lookFor: "区分事实、专业判断、方案取舍与资源优先级。" },
          { name: "证据驱动", lookFor: "用可核验信息或实验收敛，而非只靠说服。" },
          { name: "可修正性", lookFor: "证据变化后能承认错误并修正相关方案。" },
        ],
      },
    ],
  },
  {
    id: "general-ai-pm",
    title: "通用 AI 产品经理",
    description:
      "适用于通用 AI 产品岗位的精简模拟题包，覆盖问题选择、方案取舍、MVP、评测、指标、安全与跨职能协作。回答项目题时请主动脱敏，不披露可识别的个人、客户或未公开业务信息。",
    competencies: [
      "AI 机会判断",
      "AI 产品方案与 MVP",
      "质量评测与指标实验",
      "安全治理与人机协作",
      "项目所有权与跨职能协作",
    ],
    version: "1.0.0",
    questions: [
      {
        id: "general-ai-problem-selection",
        category: "AI 机会判断",
        priority: 1,
        question: "面对一个业务问题，你如何判断它是否值得用 AI 解决？",
        keywords: ["用户价值", "任务结构", "不确定性", "数据条件", "错误成本", "非 AI 基线"],
        signalGroups: {
          problem: { label: "用户问题", keywords: ["真实任务", "痛点强度", "发生频率"], required: true },
          context: { label: "可行条件", keywords: ["数据可用", "任务边界", "容错空间"], required: true },
          action: { label: "验证方法", keywords: ["人工原型", "规则基线", "小样本测试"], required: true },
          evidence: { label: "决策证据", keywords: ["质量提升", "效率收益", "用户采用"], required: true },
          judgment: { label: "方案判断", keywords: ["是否需要 AI", "能力匹配", "投入产出"], required: true },
          reflection: { label: "风险边界", keywords: ["失败后果", "人工兜底", "停止条件"], required: true },
        },
        followUps: [
          { id: "general-ai-problem-selection-f1", triggerLabel: "因为可以用 AI 就默认应该用", requires: ["problem", "judgment"], question: "什么情况下规则、搜索或流程优化会比 AI 更合适？" },
          { id: "general-ai-problem-selection-f2", triggerLabel: "只谈技术可行，缺少用户价值证据", requires: ["context", "evidence"], question: "在投入开发前，你会用什么低成本方式验证用户真的在意这个问题？" },
          { id: "general-ai-problem-selection-f3", triggerLabel: "忽略错误成本和退出条件", requires: ["action", "reflection"], question: "如果质量只能达到可用但不稳定，你如何限制场景并设置人工兜底？" },
        ],
        evaluationDimensions: [
          { name: "问题优先", lookFor: "从用户任务和价值出发，而非从模型能力反推需求。" },
          { name: "技术判断", lookFor: "比较 AI 与非 AI 基线，并说明能力适配条件。" },
          { name: "验证效率", lookFor: "先用低成本原型验证最大不确定性。" },
          { name: "风险意识", lookFor: "按错误后果限制范围并设置退出条件。" },
        ],
      },
      {
        id: "general-ai-flagship-project",
        category: "项目深挖",
        priority: 1,
        question: "请介绍一个最能代表你的 AI 产品项目，并明确你的个人贡献。",
        keywords: ["用户问题", "方案选择", "个人所有权", "质量验证", "业务结果", "复盘"],
        signalGroups: {
          problem: { label: "问题定义", keywords: ["目标用户", "核心任务", "价值假设"], required: true },
          context: { label: "项目约束", keywords: ["数据与能力", "资源", "成功标准"], required: true },
          action: { label: "个人行动", keywords: ["本人决策", "交付推进", "质量闭环"], required: true },
          evidence: { label: "结果证据", keywords: ["口径", "用户行为", "护栏表现"], required: true },
          judgment: { label: "关键取舍", keywords: ["方案比较", "范围边界", "风险权衡"], required: true },
          reflection: { label: "项目复盘", keywords: ["未达预期", "改进", "迁移方法"], required: true },
        },
        followUps: [
          { id: "general-ai-flagship-project-f1", triggerLabel: "堆叠技术名词，没有核心用户问题", requires: ["problem", "context"], question: "如果不提模型与技术名词，这个项目为谁解决了什么问题？" },
          { id: "general-ai-flagship-project-f2", triggerLabel: "个人与团队贡献边界不清", requires: ["action", "judgment"], question: "哪三个关键判断由你直接负责？哪些实现或成果不应归到你个人？" },
          { id: "general-ai-flagship-project-f3", triggerLabel: "只给结果数字，没有口径与局限", requires: ["evidence", "reflection"], question: "这些结果如何定义和验证？有哪些反例、局限或仍不能确认的因果关系？" },
        ],
        evaluationDimensions: [
          { name: "产品叙事", lookFor: "围绕用户问题、决策和结果组织项目，而非技术清单。" },
          { name: "所有权边界", lookFor: "准确区分个人判断、团队协作和专业实现。" },
          { name: "证据可信度", lookFor: "解释口径、基线、限制和未知部分。" },
          { name: "复盘深度", lookFor: "从失败和限制提炼可迁移的产品方法。" },
        ],
      },
      {
        id: "general-ai-solution-selection",
        category: "AI 方案设计",
        priority: 1,
        question: "面对同一任务，你如何在提示词、检索增强、固定工作流与自主代理之间选择方案？",
        keywords: ["任务复杂度", "知识新鲜度", "可控性", "工具调用", "成本延迟", "评测"],
        signalGroups: {
          problem: { label: "任务需求", keywords: ["输入输出", "变化程度", "成功标准"], required: true },
          context: { label: "技术约束", keywords: ["知识来源", "工具权限", "成本延迟"], required: true },
          action: { label: "选型过程", keywords: ["简单基线", "逐级增强", "原型对比"], required: true },
          evidence: { label: "方案证据", keywords: ["质量", "稳定性", "成本"], required: true },
          judgment: { label: "架构取舍", keywords: ["确定性", "自主性", "维护成本"], required: true },
          reflection: { label: "降级策略", keywords: ["失败模式", "回退", "人工接管"], required: true },
        },
        followUps: [
          { id: "general-ai-solution-selection-f1", triggerLabel: "直接选择最复杂的代理方案", requires: ["problem", "judgment"], question: "你会先建立什么最简单的基线？什么证据才值得增加自主性？" },
          { id: "general-ai-solution-selection-f2", triggerLabel: "只比较准确率，忽略系统代价", requires: ["context", "evidence"], question: "质量相近时，你如何比较时延、成本、稳定性和维护难度？" },
          { id: "general-ai-solution-selection-f3", triggerLabel: "没有失败与降级路径", requires: ["action", "reflection"], question: "检索无结果、工具失败或置信不足时，产品应该怎样降级？" },
        ],
        evaluationDimensions: [
          { name: "任务建模", lookFor: "从输入、输出、变化性和风险推导方案需求。" },
          { name: "渐进复杂度", lookFor: "从简单可测基线开始，用证据增加复杂度。" },
          { name: "系统权衡", lookFor: "综合质量、时延、成本、稳定性和维护性。" },
          { name: "可靠性设计", lookFor: "为关键失败模式准备降级和人工接管。" },
        ],
      },
      {
        id: "general-ai-mvp",
        category: "AI 方案设计",
        priority: 1,
        question: "你会如何定义一个 AI 产品的 MVP，使它既能验证价值又不掩盖质量风险？",
        keywords: ["最大不确定性", "窄任务", "人工服务", "能力边界", "质量门槛", "扩展条件"],
        signalGroups: {
          problem: { label: "验证问题", keywords: ["最大不确定性", "用户任务", "价值假设"], required: true },
          context: { label: "MVP 条件", keywords: ["目标用户", "数据范围", "风险等级"], required: true },
          action: { label: "最小方案", keywords: ["窄场景", "人工兜底", "可观察流程"], required: true },
          evidence: { label: "验证标准", keywords: ["任务成功", "质量门槛", "重复使用"], required: true },
          judgment: { label: "范围边界", keywords: ["主动不做", "发布限制", "扩展条件"], required: true },
          reflection: { label: "失败学习", keywords: ["退出条件", "坏样本", "假设更新"], required: true },
        },
        followUps: [
          { id: "general-ai-mvp-f1", triggerLabel: "MVP 是缩小版功能清单，没有验证目标", requires: ["problem", "evidence"], question: "这个 MVP 最需要回答哪一个问题？你如何在短周期内获得可信证据？" },
          { id: "general-ai-mvp-f2", triggerLabel: "没有明确用户、数据和能力边界", requires: ["context", "judgment"], question: "一期支持哪些输入与任务，明确不支持什么，用户如何感知边界？" },
          { id: "general-ai-mvp-f3", triggerLabel: "用人工兜底隐藏产品质量问题", requires: ["action", "reflection"], question: "人工参与如何被记录和计入成本，避免形成虚假的自动化效果？" },
        ],
        evaluationDimensions: [
          { name: "验证聚焦", lookFor: "围绕最大不确定性而非完整愿景定义 MVP。" },
          { name: "边界透明", lookFor: "明确支持范围、失败方式和用户预期。" },
          { name: "真实成本", lookFor: "将人工兜底、运营和修复成本纳入验证。" },
          { name: "扩展纪律", lookFor: "用明确证据决定继续、扩展或停止。" },
        ],
      },
      {
        id: "general-ai-evaluation",
        category: "评测与迭代",
        priority: 1,
        question: "你会如何搭建 AI 产品的离线评测、线上监控与坏样本迭代闭环？",
        keywords: ["任务分层", "评测集", "离线指标", "线上行为", "坏样本归因", "回归"],
        signalGroups: {
          problem: { label: "质量定义", keywords: ["任务成功", "关键错误", "用户后果"], required: true },
          context: { label: "样本覆盖", keywords: ["真实分布", "长尾边界", "高风险样本"], required: true },
          action: { label: "评测流程", keywords: ["离线门禁", "线上监控", "归因回归"], required: true },
          evidence: { label: "评判证据", keywords: ["可核验预期", "行为指标", "人工复核"], required: true },
          judgment: { label: "指标取舍", keywords: ["总体分数", "分层指标", "发布阈值"], required: true },
          reflection: { label: "评测维护", keywords: ["数据漂移", "污染防范", "版本治理"], required: true },
        },
        followUps: [
          { id: "general-ai-evaluation-f1", triggerLabel: "用单一准确率代表全部质量", requires: ["problem", "judgment"], question: "哪些错误虽然少见但必须单独设门槛？为什么平均分会掩盖它们？" },
          { id: "general-ai-evaluation-f2", triggerLabel: "评测集只有常规样本或静态样本", requires: ["context", "reflection"], question: "如何覆盖边界与高风险样本，并防止评测集过期或被针对性优化？" },
          { id: "general-ai-evaluation-f3", triggerLabel: "离线、线上和迭代彼此割裂", requires: ["action", "evidence"], question: "一个线上坏样本怎样进入归因、修复、回归和新版本发布门禁？" },
        ],
        evaluationDimensions: [
          { name: "质量建模", lookFor: "将任务成功、关键错误和用户后果转成分层标准。" },
          { name: "样本策略", lookFor: "兼顾真实分布、边界、长尾与高风险场景。" },
          { name: "端到端闭环", lookFor: "连接离线评测、线上监控、人工复核与回归。" },
          { name: "持续治理", lookFor: "管理评测版本、漂移与针对测试集过拟合的风险。" },
        ],
      },
      {
        id: "general-ai-metrics-experiment",
        category: "指标与实验",
        priority: 2,
        question: "你会如何证明一项 AI 功能改善了用户结果，而不只是提高了调用量？",
        keywords: ["任务结果", "质量指标", "行为链路", "对照实验", "选择偏差", "护栏"],
        signalGroups: {
          problem: { label: "价值假设", keywords: ["用户任务", "原流程问题", "目标结果"], required: true },
          context: { label: "实验语境", keywords: ["用户分层", "任务频率", "学习效应"], required: true },
          action: { label: "实验设计", keywords: ["随机对照", "分阶段开放", "前后比较"], required: true },
          evidence: { label: "指标链路", keywords: ["任务完成", "返工", "持续采用"], required: true },
          judgment: { label: "因果判断", keywords: ["替代解释", "新奇效应", "样本偏差"], required: true },
          reflection: { label: "风险护栏", keywords: ["严重错误", "投诉", "成本延迟"], required: true },
        },
        followUps: [
          { id: "general-ai-metrics-experiment-f1", triggerLabel: "只有使用次数或满意度", requires: ["problem", "evidence"], question: "请把指标从一次调用延伸到任务完成、返工和后续行为。" },
          { id: "general-ai-metrics-experiment-f2", triggerLabel: "默认使用者表现好就是功能有效", requires: ["context", "judgment"], question: "主动使用者本来就更熟练时，你如何降低选择偏差？" },
          { id: "general-ai-metrics-experiment-f3", triggerLabel: "只看收益，缺少质量与成本护栏", requires: ["action", "reflection"], question: "什么质量、安全、时延或成本变化会让你停止实验？" },
        ],
        evaluationDimensions: [
          { name: "指标链路", lookFor: "从调用延伸到质量、任务结果和持续采用。" },
          { name: "实验设计", lookFor: "根据条件选择对照、分阶段或准实验方法。" },
          { name: "因果意识", lookFor: "识别选择偏差、新奇效应和外部变化。" },
          { name: "风险收益", lookFor: "同步观察严重错误、投诉、时延和成本。" },
        ],
      },
      {
        id: "general-ai-safety",
        category: "安全与治理",
        priority: 1,
        question: "设计一个会读取业务数据并调用工具的 AI 产品时，你会建立哪些安全与治理机制？",
        keywords: ["最小权限", "数据隔离", "提示注入", "工具白名单", "人工确认", "审计回滚"],
        signalGroups: {
          problem: { label: "威胁识别", keywords: ["数据泄露", "恶意输入", "错误动作"], required: true },
          context: { label: "风险语境", keywords: ["数据敏感度", "动作可逆性", "影响范围"], required: true },
          action: { label: "防护机制", keywords: ["最小授权", "输入隔离", "执行前校验"], required: true },
          evidence: { label: "安全证据", keywords: ["对抗测试", "审计日志", "事件监控"], required: true },
          judgment: { label: "风险分级", keywords: ["自动执行", "人工确认", "禁止动作"], required: true },
          reflection: { label: "事件响应", keywords: ["撤销回滚", "影响追踪", "策略更新"], required: true },
        },
        followUps: [
          { id: "general-ai-safety-f1", triggerLabel: "只提内容审核，忽略权限和工具风险", requires: ["problem", "context"], question: "读取数据、生成内容和执行动作分别有哪些不同风险？" },
          { id: "general-ai-safety-f2", triggerLabel: "用一次性确认替代持续权限校验", requires: ["action", "judgment"], question: "工具每次执行前应重新检查什么？哪些动作即使授权也不应自动执行？" },
          { id: "general-ai-safety-f3", triggerLabel: "没有测试、审计和事故恢复", requires: ["evidence", "reflection"], question: "上线前怎样对抗测试？出错后如何确定影响范围、撤销动作并更新防护？" },
        ],
        evaluationDimensions: [
          { name: "威胁模型", lookFor: "覆盖泄露、注入、越权、误操作和间接推断。" },
          { name: "分层防护", lookFor: "在数据、指令、工具与输出各层设置控制。" },
          { name: "风险分级", lookFor: "按敏感度、可逆性和影响范围决定自动化程度。" },
          { name: "可恢复性", lookFor: "具备测试、监控、审计、撤销和事件复盘机制。" },
        ],
      },
      {
        id: "general-ai-collaboration",
        category: "协作与复盘",
        priority: 2,
        question: "当业务希望尽快上线、算法认为质量不足、工程担心稳定性时，你会如何推动决策？",
        keywords: ["共同目标", "争议拆解", "证据缺口", "风险分层", "灰度方案", "决策责任"],
        signalGroups: {
          problem: { label: "冲突定义", keywords: ["价值速度", "质量门槛", "稳定性风险"], required: true },
          context: { label: "各方约束", keywords: ["业务窗口", "样本证据", "工程能力"], required: true },
          action: { label: "推进方案", keywords: ["共同指标", "灰度范围", "应急预案"], required: true },
          evidence: { label: "决策证据", keywords: ["质量分层", "压测", "用户验证"], required: true },
          judgment: { label: "责任与取舍", keywords: ["不可妥协底线", "风险接受者", "最终决策人"], required: true },
          reflection: { label: "复盘机制", keywords: ["上线门禁", "监控阈值", "流程改进"], required: true },
        },
        followUps: [
          { id: "general-ai-collaboration-f1", triggerLabel: "把冲突归结为沟通不充分", requires: ["problem", "context"], question: "三方各自掌握什么事实、承担什么风险，还缺少哪项关键证据？" },
          { id: "general-ai-collaboration-f2", triggerLabel: "只给全量上线或完全延期两个选择", requires: ["action", "evidence"], question: "能否通过收窄用户、任务或动作权限设计一个可控的灰度方案？" },
          { id: "general-ai-collaboration-f3", triggerLabel: "没有底线、决策归属和复盘", requires: ["judgment", "reflection"], question: "哪些底线不可妥协，谁接受剩余风险，什么信号会触发回滚？" },
        ],
        evaluationDimensions: [
          { name: "冲突拆解", lookFor: "区分价值、质量、稳定性和资源问题。" },
          { name: "证据组织", lookFor: "明确已知、未知和获得关键证据的最短路径。" },
          { name: "方案能力", lookFor: "通过范围、权限、灰度和预案平衡速度与风险。" },
          { name: "决策治理", lookFor: "明确底线、风险接受者、最终责任人和回滚条件。" },
        ],
      },
    ],
  },
  {
    id: "tencent-pm-comprehensive",
    title: "腾讯产品经理 · 综合面经",
    description:
      "基于公开面经主题去重整理的综合模拟题库，覆盖个人定位、项目深挖、产品判断、AI 场景、协作复盘与反问。参考答案仅作结构示例，涉及经历时请替换为可公开、可核验的个人事实。",
    competencies: [
      "个人定位与岗位动机",
      "项目判断与完整闭环",
      "跨团队协作与复盘",
      "用户洞察与产品设计",
      "AI 产品与评测方法",
      "优先级与价值判断",
    ],
    version: "1.0.0",
    canonicalModules: [
      { id: "M1", title: "自我介绍", sourceRefs: ["S1-01", "S2-01"] },
      { id: "M2", title: "代表项目完整深挖", sourceRefs: ["L01", "L09", "L10", "L11", "L14", "L15", "L16", "L17", "S1-02", "S1-06", "S2-06", "S2-12"] },
      { id: "M3", title: "分歧与跨团队推进", sourceRefs: ["L02", "S1-04"] },
      { id: "M4", title: "失败与复盘", sourceRefs: ["L04"] },
      { id: "M5", title: "产品诊断与用户反馈", sourceRefs: ["L03", "S1-12"] },
      { id: "M6", title: "角色认知与个人适配", sourceRefs: ["L05", "S1-09", "S1-11", "S2-17"] },
      { id: "M7", title: "公司动机与职业规划", sourceRefs: ["L06", "L07", "L12", "S2-13"] },
      { id: "M8", title: "AI 产品设计与评测", sourceRefs: ["L13", "S2-07", "S2-08", "S2-09", "S2-10", "S2-11"] },
      { id: "M9", title: "产品感与趋势判断", sourceRefs: ["L18", "L19", "L20", "S1-08", "S1-10", "S2-02", "S2-03", "S2-04", "S2-05", "S2-14"] },
      { id: "M10", title: "支付与扫码点餐场景", sourceRefs: ["L21", "S2-15", "S2-16"] },
      { id: "M11", title: "优先级、数据与价值", sourceRefs: ["S1-03", "S1-05", "S1-07"] },
      { id: "M12", title: "反问", sourceRefs: ["L08"] },
    ],
    sourceCoverage: {
      total: 50,
      groups: { textList: 21, screenshot1: 12, screenshot2: 17 },
      note: "50 个来源问法均映射到 M1—M12 的主问题或自然追问；同一来源只在模块清单中计数一次。",
    },
    interviewFlow: {
      15: ["tencent-introduction", "tencent-project-overview", "tencent-product-diagnosis", "tencent-reverse"],
      30: ["tencent-introduction", "tencent-project-overview", "tencent-project-problem-value", "tencent-project-design-delivery", "tencent-ai-product-design", "tencent-role-fit", "tencent-reverse"],
      45: ["tencent-introduction", "tencent-project-overview", "tencent-project-problem-value", "tencent-project-design-delivery", "tencent-project-validation", "tencent-disagreement", "tencent-product-diagnosis", "tencent-ai-product-design", "tencent-priority-value", "tencent-reverse"],
    },
    interviewFlowVariants: {
      15: [
        { id: "project-product", flow: ["tencent-introduction", "tencent-project-overview", "tencent-product-diagnosis", "tencent-reverse"] },
        { id: "project-ai", flow: ["tencent-introduction", "tencent-project-overview", "tencent-ai-product-design", "tencent-reverse"] },
        { id: "project-personal-thread", flow: ["tencent-introduction", "tencent-personal-thread", "tencent-project-overview", "tencent-reverse"] },
      ],
      30: [
        { id: "project-product-ai", flow: ["tencent-introduction", "tencent-project-overview", "tencent-project-problem-value", "tencent-project-design-delivery", "tencent-favorite-product", "tencent-ai-product-design", "tencent-reverse"] },
        { id: "project-behavior-fit", flow: ["tencent-introduction", "tencent-project-overview", "tencent-project-validation", "tencent-project-retrospective", "tencent-disagreement", "tencent-role-fit", "tencent-reverse"] },
        { id: "project-scenario-growth", flow: ["tencent-introduction", "tencent-project-overview", "tencent-project-problem-value", "tencent-project-validation", "tencent-journal-product", "tencent-qr-ordering", "tencent-reverse"] },
      ],
      45: [
        { id: "comprehensive-core", flow: ["tencent-introduction", "tencent-project-overview", "tencent-project-problem-value", "tencent-project-design-delivery", "tencent-project-validation", "tencent-disagreement", "tencent-product-diagnosis", "tencent-ai-product-design", "tencent-priority-value", "tencent-reverse"] },
        { id: "comprehensive-behavior", flow: ["tencent-introduction", "tencent-project-overview", "tencent-project-validation", "tencent-project-retrospective", "tencent-failure-retrospective", "tencent-feedback-iteration", "tencent-role-boundary", "tencent-company-motivation", "tencent-career-plan", "tencent-reverse"] },
        { id: "comprehensive-ai-scenario", flow: ["tencent-introduction", "tencent-project-overview", "tencent-project-problem-value", "tencent-project-design-delivery", "tencent-project-validation", "tencent-ai-product-design", "tencent-ai-skill-mcp", "tencent-ai-evaluation", "tencent-payment-experience", "tencent-reverse"] },
      ],
    },
    questions: [
      {
        id: "tencent-introduction",
        moduleId: "M1", category: "开场", priority: 0, maxFollowUps: 0, evaluationProfile: "introduction",
        question: "先简单介绍一下自己吧。",
        keywords: ["经历主线", "代表项目", "岗位能力"],
        signalGroups: { context: { label: "个人背景", keywords: ["方向", "经历"], required: true }, action: { label: "经历主线", keywords: ["负责", "项目"], required: true }, judgment: { label: "能力定位", keywords: ["擅长", "优势"], required: true } },
        answerFramework: ["一句交代身份与毕业时间", "先讲最近、最匹配岗位的 AI 数据产品实习", "一句补充此前经历，再落到两到三个能力优势"],
        referenceAnswer: "面试官您好，我目前是研三在读，27 届应届生。之前我在一家大型互联网公司的全球电商团队实习，主要做 B 端 AI 数据产品，核心项目是一款面向业务人员的取数分析 Agent。我具体参与了指标知识库、分析 Skill 和自动化测评的建设，帮助 Agent 更准确地理解指标、完成取数和经营分析。除了 Agent 项目，我也承接过看板、预警和数据组件等基础数据产品需求；更早之前，我做过电商内容场的经营分析。这些经历让我形成了比较复合的产品能力：既懂业务和数据，也能把复杂问题抽象成产品方案，再通过数据和评测持续验证效果。",
        sourceRefs: ["S1-01", "S2-01"], followUps: [],
        evaluationDimensions: [{ name: "信息取舍", lookFor: "一分钟内形成清晰主线。" }, { name: "岗位相关", lookFor: "能力与产品岗位自然连接。" }, { name: "表达真实", lookFor: "不堆经历与数字。" }],
      },
      {
        id: "tencent-personal-thread",
        moduleId: "M1", category: "个人定位", priority: 1,
        question: "你这些经历之间，最稳定的一条主线是什么？",
        keywords: ["问题变化", "能力递进", "产品判断"],
        signalGroups: { context: { label: "经历变化", keywords: ["从", "到"], required: true }, action: { label: "能力递进", keywords: ["分析", "产品化", "验证"], required: true }, judgment: { label: "稳定主线", keywords: ["不变", "核心"], required: true } },
        answerFramework: ["区分变化的场景和不变的问题", "说明责任从一次交付到持续机制的递进", "收束为一句产品特点"],
        referenceAnswer: "场景在变化，但主线一直是先理解用户为什么卡住，再把解决方法沉淀成能被重复使用的机制。我的责任也从给出一次判断，逐步扩展到需求取舍、跨角色协作和上线后的质量验证。我的产品特点，是能把业务语言翻译成清晰规则，并对结果是否真正可用负责。",
        sourceRefs: ["S1-01", "S2-01"],
        followUps: [{ id: "tencent-personal-thread-f1", triggerLabel: "只复述岗位名称，没有能力递进", requires: ["action", "judgment"], question: "那你解决问题的方式具体变了什么？", answerFramework: ["过去做法", "现在新增的判断责任", "一个可验证变化"], referenceAnswer: "过去我更关注把一个问题解释清楚；现在还会判断问题是否高频、是否值得标准化、怎样交给团队稳定实现，以及上线后用什么证据验证。变化不是少做分析，而是开始对取舍和持续结果负责。" }],
        evaluationDimensions: [{ name: "主线清晰", lookFor: "不是简历复述。" }, { name: "能力递进", lookFor: "体现责任范围扩大。" }],
      },
      {
        id: "tencent-project-overview", projectSpineId: "tencent-project-deep-dive",
        moduleId: "M2", category: "项目深挖", priority: 0,
        question: "挑一件最能代表你产品能力的事，完整讲讲。",
        keywords: ["用户问题", "个人贡献", "关键取舍", "结果", "复盘"],
        signalGroups: { problem: { label: "核心问题", keywords: ["用户", "痛点"], required: true }, context: { label: "背景约束", keywords: ["原流程", "约束"], required: true }, action: { label: "个人行动", keywords: ["我负责", "推动"], required: true }, evidence: { label: "结果证据", keywords: ["验证", "结果"], required: true }, judgment: { label: "关键取舍", keywords: ["选择", "取舍"], required: true }, reflection: { label: "复盘", keywords: ["复盘", "改进"], required: true } },
        answerFramework: ["用户与旧流程", "目标和本人边界", "关键判断与落地", "结果证据、限制和复盘"],
        referenceAnswer: "我想讲一个把重复人工流程做成通用能力的项目。用户原先需要在多个入口间查找信息、反复确认规则，问题不只是慢，还容易产生理解偏差。我负责梳理核心任务、定义一期边界，并组织产品、设计和研发共同评审。我们先用小范围原型验证最关键链路，再逐步补齐权限、异常与反馈机制。上线后通过任务是否完成、返工是否减少和用户是否持续使用来判断效果。复盘看，我会更早验证边界场景，避免主流程成立后才发现例外成本。",
        sourceRefs: ["L01", "S1-02", "S2-06"],
        followUps: [
          { id: "tencent-project-overview-f1", triggerLabel: "大量使用我们，个人边界不清", requires: ["action"], question: "你在里面具体负责什么？", answerFramework: ["明确负责范围", "列出亲自完成的关键动作", "区分团队结果"], referenceAnswer: "我直接负责用户问题梳理、方案范围和验收标准，也推动关键角色在同一版流程上达成共识；视觉方案和工程实现由对应同学负责。最终结果属于团队，我只把自己实际做出的判断和交付讲清楚。" },
          { id: "tencent-project-overview-f2", triggerLabel: "项目叙述像功能清单", requires: ["problem", "judgment"], question: "你做过最关键的一个判断是什么？", answerFramework: ["当时有哪些选项", "依据与风险", "为什么选当前方案"], referenceAnswer: "最关键的判断是先解决高频且可验证的核心任务，而不是一次覆盖所有需求。这样能用最小成本验证用户是否真的愿意改变原流程，也为后续扩展保留依据；代价是一些低频需求需要暂时用人工方案承接。" },
        ],
        evaluationDimensions: [{ name: "完整闭环", lookFor: "问题、行动、结果、复盘相连。" }, { name: "所有权", lookFor: "个人贡献边界清楚。" }, { name: "决策质量", lookFor: "存在真实取舍。" }],
      },
      {
        id: "tencent-project-problem-value", projectSpineId: "tencent-project-deep-dive",
        moduleId: "M2", category: "项目深挖", priority: 0,
        question: "这个项目到底解决了什么问题，为什么值得做？",
        keywords: ["目标用户", "旧方案", "问题频率", "投入价值"],
        signalGroups: { problem: { label: "真实痛点", keywords: ["卡点", "损失"], required: true }, context: { label: "用户场景", keywords: ["用户", "流程"], required: true }, evidence: { label: "价值证据", keywords: ["频率", "影响"], required: true }, judgment: { label: "投入判断", keywords: ["值得", "不做"], required: true } },
        answerFramework: ["还原用户任务和旧方案", "说明问题频率与失败后果", "比较继续人工、局部优化和产品化", "给出值得投入的验证条件"],
        referenceAnswer: "核心问题不是缺一个入口，而是同类任务反复发生时，信息和判断标准都无法稳定复用。继续靠人工可以应急，但成本会随使用范围增长，且质量依赖个人经验。我们判断值得做，是因为任务高频、错误会影响后续决策，并且可以先在窄场景验证；如果持续使用和任务质量没有改善，就不应继续扩大。",
        sourceRefs: ["L09", "L10", "L14"],
        followUps: [
          { id: "tencent-project-problem-value-f1", triggerLabel: "只说效率低，没有还原旧流程", requires: ["problem", "context"], question: "原来靠人工为什么不够？", answerFramework: ["人工方案适用边界", "规模扩大后的问题", "产品化要解决的稳定性"], referenceAnswer: "人工在低频、规则未稳定时很有效，但任务重复后会出现标准不一、知识难维护和交接成本。产品化的价值不是消灭人工，而是把稳定共性沉淀下来，把例外留给澄清和人工判断。" },
          { id: "tencent-project-problem-value-f2", triggerLabel: "用愿景替代投入证据", requires: ["evidence", "judgment"], question: "什么信号会让你决定不继续做？", answerFramework: ["设定停止条件", "区分需求不存在和方案错误", "说明后续动作"], referenceAnswer: "如果目标用户在真实任务中没有持续使用，或任务质量的改善不足以覆盖迁移与维护成本，我会停止扩张，先判断是假设错误还是方案摩擦；只有找到可验证的新证据才继续投入。" },
        ],
        evaluationDimensions: [{ name: "问题定义", lookFor: "从用户任务而非功能出发。" }, { name: "价值判断", lookFor: "有投入与停止条件。" }],
      },
      {
        id: "tencent-project-design-delivery", projectSpineId: "tencent-project-deep-dive",
        moduleId: "M2", category: "项目深挖", priority: 0,
        question: "你的设计逻辑是什么，方案怎么一步步落地？",
        keywords: ["设计原则", "核心节点", "阶段拆解", "依赖", "验收"],
        signalGroups: { context: { label: "约束依赖", keywords: ["约束", "依赖"], required: true }, action: { label: "落地步骤", keywords: ["先", "再", "上线"], required: true }, evidence: { label: "阶段验收", keywords: ["验证", "验收"], required: true }, judgment: { label: "设计原则", keywords: ["原则", "取舍"], required: true } },
        answerFramework: ["先给一条设计原则", "拆出核心对象和主链路", "按风险安排原型、灰度和扩展", "每阶段绑定验收信号"],
        referenceAnswer: "设计原则是先让核心任务闭环，再增加覆盖面。第一步确认用户、输入和期望结果；第二步用低成本原型验证最不确定的节点；第三步补齐权限、异常、状态反馈和必要的数据记录；最后小范围上线，以真实任务结果决定是否扩展。这样每一步都有交付，也避免把未经验证的假设固化成复杂系统。",
        sourceRefs: ["L11", "L15"],
        followUps: [
          { id: "tencent-project-design-delivery-f1", triggerLabel: "方案一步到位，没有阶段验证", requires: ["action", "evidence"], question: "如果只能先做一小步，你保留什么？", answerFramework: ["指出最大不确定性", "保留最短任务闭环", "明确主动不做项"], referenceAnswer: "我会保留能验证核心价值的最短链路：让一类目标用户完成一次真实任务并得到可判断结果。复杂配置、低频例外和规模化能力先不做，但会记录需求触发条件，避免一期范围失控。" },
          { id: "tencent-project-design-delivery-f2", triggerLabel: "只讲页面，没有异常与依赖", requires: ["context", "judgment"], question: "最容易把项目拖垮的依赖是什么？", answerFramework: ["识别关键依赖", "说明前置验证", "准备降级方案"], referenceAnswer: "最危险的通常是核心数据、权限或跨团队接口尚未确认，却按理想状态设计全流程。我会把它前置成验证项，明确负责人和截止点，同时准备只读、人工确认或缩小范围的降级路径。" },
        ],
        evaluationDimensions: [{ name: "拆解能力", lookFor: "步骤围绕风险而非页面。" }, { name: "落地意识", lookFor: "依赖、异常和验收齐全。" }],
      },
      {
        id: "tencent-project-validation", projectSpineId: "tencent-project-deep-dive",
        moduleId: "M2", category: "项目深挖", priority: 0,
        question: "你怎么判断项目真的做成了？讲一个坏案例。",
        keywords: ["任务结果", "指标口径", "坏案例", "根因", "回归"],
        signalGroups: { problem: { label: "失败表现", keywords: ["错误", "偏差"], required: true }, action: { label: "归因修复", keywords: ["定位", "修复"], required: true }, evidence: { label: "验证证据", keywords: ["任务完成", "回归"], required: true }, reflection: { label: "质量闭环", keywords: ["回流", "预防"], required: true } },
        answerFramework: ["用知识、能力、用户任务三层定义成功", "用脱敏坏案例说明预期与实际", "定位根因并修复", "原案例和相邻案例一起回归"],
        referenceAnswer: "我不会用交付完成或调用次数代表成功，而会看输入是否可靠、关键步骤是否正确，以及用户最终任务是否完成。一个可公开的坏案例是：同义表达让系统选错对象，表面答案通顺但结论不可用。我们先核对预期，再定位到语义区分不足，补充澄清条件和测试样本，并用原问题及相邻表达回归。高风险情形在修复前必须停止执行或转人工确认。",
        sourceRefs: ["L16"],
        followUps: [
          { id: "tencent-project-validation-f1", triggerLabel: "只报结果，没有口径", requires: ["evidence"], question: "这个结果的口径为什么可信？", answerFramework: ["定义样本和分母", "说明基线与观察周期", "交代已知局限"], referenceAnswer: "我会先说明对象、样本和成功定义，再说明比较基线与观察周期。若样本存在选择偏差或周期不足，也会直接交代；没有正式口径时，只描述可观察变化，不现场补一个漂亮数字。" },
          { id: "tencent-project-validation-f2", triggerLabel: "修复一个案例后就宣布解决", requires: ["action", "reflection"], question: "怎么避免修好这一条、弄坏另一批？", answerFramework: ["按根因建立同类样本", "执行回归", "设发布与回滚条件"], referenceAnswer: "我会按根因补同义、边界和反例样本，既验证原案例，也检查相关任务是否退化。发布时保留版本、监控和回滚条件，让修复从一次补丁变成可持续的质量规则。" },
        ],
        evaluationDimensions: [{ name: "结果可信", lookFor: "指标口径与用户结果相连。" }, { name: "归因能力", lookFor: "坏案例有预期、实际、根因和回归。" }],
      },
      {
        id: "tencent-project-retrospective", projectSpineId: "tencent-project-deep-dive",
        moduleId: "M2", category: "项目深挖", priority: 1,
        question: "如果重做一次，你会改什么？这个项目让你成长了什么？",
        keywords: ["重做", "机制改进", "能力成长", "团队定位"],
        signalGroups: { context: { label: "原决策", keywords: ["当时", "原来"], required: true }, judgment: { label: "重做选择", keywords: ["会先", "调整"], required: true }, reflection: { label: "成长迁移", keywords: ["学到", "以后"], required: true } },
        answerFramework: ["指出一个当时可改的判断", "说明更早采取的具体动作", "讲清形成的新机制", "收束为可迁移能力"],
        referenceAnswer: "如果重做，我会更早明确哪些信息适合标准化、哪些仍需要人工判断，并在扩展前建立一组代表性回归案例。这样既避免过早固化变化快的规则，也减少规模扩大后的重复治理。最大的成长是，我开始把产品上线、质量发现和错误恢复视为一个整体，而不是把交付当作终点。",
        sourceRefs: ["L17", "S1-06", "S2-12"],
        followUps: [
          { id: "tencent-project-retrospective-f1", triggerLabel: "复盘像事后正确答案", requires: ["context", "reflection"], question: "这项改进后来真的进入你的工作方式了吗？", answerFramework: ["给出后续场景", "说明行为变化", "提供可观察证据"], referenceAnswer: "后来遇到相似项目时，我会在方案评审前先列高风险假设和代表性案例，并把异常处理写入验收。即使暂时没有完整结果，也能用评审记录、提前暴露的问题和减少的返工证明方法确实改变了。" },
          { id: "tencent-project-retrospective-f2", triggerLabel: "夸大团队或组织意义", requires: ["judgment"], question: "你们在整个协作链路里是什么角色？", answerFramework: ["只讲亲历分工", "说明上下游接口", "不替组织下战略结论"], referenceAnswer: "我能确认的角色，是把用户问题转成明确规则和可验收能力，并连接业务判断与技术实现。数据、工程和专业口径分别由对应负责人承担；对超出本人经历的组织定位，我会明确作为待确认信息。" },
        ],
        evaluationDimensions: [{ name: "复盘真实", lookFor: "能回到当时条件。" }, { name: "方法迁移", lookFor: "形成后续行动变化。" }],
      },
      {
        id: "tencent-disagreement", moduleId: "M3", category: "协作推进", priority: 1,
        question: "讲一次你和开发、设计或业务有明显分歧的经历。",
        keywords: ["共同目标", "分歧本质", "证据", "取舍", "推进"],
        signalGroups: { problem: { label: "具体分歧", keywords: ["分歧", "方案"], required: true }, context: { label: "各方约束", keywords: ["成本", "风险"], required: true }, action: { label: "推进动作", keywords: ["验证", "对齐"], required: true }, evidence: { label: "决策结果", keywords: ["结果", "反馈"], required: true }, judgment: { label: "共同取舍", keywords: ["保留", "后置"], required: true } },
        answerFramework: ["讲清双方观点和共同目标", "把立场拆成可验证假设", "用数据、原型或成本评估收敛", "交代共同修正后的方案"],
        referenceAnswer: "这类题必须替换成你的真实经历。一个合格答案应说明：你主张什么，对方担心什么，共同目标如何确定，你用哪类证据把争议拆开，最后保留和放弃了什么。重点不是证明你说服了别人，而是说明方案如何在用户价值、交付成本和风险之间被共同修正。",
        sourceRefs: ["L02", "S1-04"],
        followUps: [
          { id: "tencent-disagreement-f1", triggerLabel: "把协作讲成沟通态度", requires: ["action", "evidence"], question: "你靠什么证据推动判断变化？", answerFramework: ["指出争议假设", "选择最低成本证据", "说明证据如何影响方案"], referenceAnswer: "可从真实项目中选择任务样例、用户反馈、原型测试、工作量评估或风险数据。回答时要说清它验证了哪个假设，以及它如何具体改变了最终方案；不要只说\"我充分沟通后达成一致\"。" },
          { id: "tencent-disagreement-f2", triggerLabel: "只强调自己坚持成功", requires: ["judgment"], question: "最后你让步了什么？", answerFramework: ["承认对方有效判断", "区分底线和可后置项", "说明让步价值"], referenceAnswer: "请按真实决策回答：明确你接受了对方哪项合理判断，哪些范围因此被后置或删除；再说明你坚持的用户价值或安全底线。没有发生让步时，也应解释证据为何支持原方案，而不是编造妥协。" },
        ],
        evaluationDimensions: [{ name: "冲突拆解", lookFor: "不归因为性格。" }, { name: "影响力", lookFor: "依靠证据而非职级。" }],
      },
      {
        id: "tencent-failure-retrospective", moduleId: "M4", category: "失败复盘", priority: 1,
        question: "讲一次结果没达到预期、而且你要承担责任的经历。",
        keywords: ["原预期", "实际偏差", "判断责任", "补救", "机制变化"],
        signalGroups: { problem: { label: "结果偏差", keywords: ["预期", "偏差"], required: true }, action: { label: "补救行动", keywords: ["补救", "调整"], required: true }, evidence: { label: "实际结果", keywords: ["结果", "影响"], required: true }, judgment: { label: "本人责任", keywords: ["我忽略", "判断"], required: true }, reflection: { label: "机制改进", keywords: ["以后", "机制"], required: true } },
        answerFramework: ["原预期与实际偏差", "本人本可更早识别的判断失误", "补救与影响控制", "后续机制变化"],
        referenceAnswer: "这类题不能套用虚构故事。请从真实项目中选择一次结果偏差，按\"原预期—实际结果—我本可更早发现的信号—补救动作—后来新增的机制\"回答。若结果由多人共同造成，也要只承担自己负责的判断，不把资源或用户当成唯一原因。",
        sourceRefs: ["L04"],
        followUps: [
          { id: "tencent-failure-retrospective-f1", triggerLabel: "把原因推给资源或用户", requires: ["judgment"], question: "哪一步是你当时本来可以发现的？", answerFramework: ["指出具体决策点", "说明错误信号", "承担判断责任"], referenceAnswer: "回到真实项目中的一个具体决策点，说明当时有哪些信号已经出现、你为何没有重视，以及你本可以通过什么低成本动作更早发现。答案必须落到自己的判断责任，不能只归因为资源不足或用户不会用。" },
          { id: "tencent-failure-retrospective-f2", triggerLabel: "只说吸取教训", requires: ["reflection"], question: "复盘后真正改变了什么？", answerFramework: ["具体机制", "应用节点", "如何检查执行"], referenceAnswer: "不要只说\"以后更细心\"。请说明你后来新增了哪项可执行机制，例如前置验证、分层灰度、验收清单或停止条件；再用一个后续场景证明这项机制确实进入了工作方式。" },
        ],
        evaluationDimensions: [{ name: "责任意识", lookFor: "不回避本人判断。" }, { name: "复盘深度", lookFor: "形成机制变化。" }],
      },
      {
        id: "tencent-product-diagnosis", moduleId: "M5", category: "产品诊断", priority: 1,
        question: "选一个你深入用过的产品，它最大的短板是什么？",
        keywords: ["真实任务", "关键阻力", "证据", "根因假设", "改进"],
        signalGroups: { problem: { label: "具体短板", keywords: ["步骤", "阻力"], required: true }, context: { label: "使用场景", keywords: ["任务", "用户"], required: true }, action: { label: "最小改动", keywords: ["先改", "方案"], required: true }, evidence: { label: "验证证据", keywords: ["反馈", "验证"], required: true }, judgment: { label: "优先依据", keywords: ["影响", "成本"], required: true } },
        answerFramework: ["给出真实任务而非泛泛喜好", "定位短板发生的具体步骤", "说明证据与根因假设", "提出一个最小改动及验证"],
        referenceAnswer: "我会选一款自己长期用于整理资料的公开工具。它的优点是输入方便，但最大短板发生在再次查找：保存时缺少用途上下文，内容多后很难复用。这个判断目前来自连续使用记录，仍需访谈更多用户验证。我会先增加轻量的保存意图和后续任务入口，用查找成功、复用行为与额外操作成本判断是否有效。",
        sourceRefs: ["L03"],
        followUps: [{ id: "tencent-product-diagnosis-f1", triggerLabel: "把个人不喜欢当成普遍问题", requires: ["evidence"], question: "怎么证明这不是你的个人偏好？", answerFramework: ["承认当前证据等级", "补任务数据和重复反馈", "说明何种证据会推翻假设"], referenceAnswer: "如果只有我的体验，我会明确称它为假设。下一步看关键步骤的失败情况、访谈不同熟练度用户，并比较替代方案；如果多数目标用户能顺利完成任务，或问题只存在于小众习惯，我会降低优先级。" }],
        evaluationDimensions: [{ name: "洞察质量", lookFor: "从任务链路定位问题。" }, { name: "验证意识", lookFor: "区分事实和假设。" }],
      },
      {
        id: "tencent-feedback-iteration", moduleId: "M5", category: "用户研究", priority: 2,
        question: "讲一个你根据用户反馈调整方案的例子。",
        keywords: ["反馈来源", "问题归类", "方案调整", "结果验证"],
        signalGroups: { problem: { label: "反馈问题", keywords: ["反馈", "问题"], required: true }, context: { label: "用户任务", keywords: ["用户", "场景"], required: true }, action: { label: "分析与改动", keywords: ["归类", "调整"], required: true }, evidence: { label: "验证结果", keywords: ["回访", "任务"], required: true }, judgment: { label: "取舍", keywords: ["没有直接做", "优先"], required: true } },
        answerFramework: ["反馈发生在什么任务", "先找反馈背后的共性根因", "说明取舍和改动", "回到同类用户验证"],
        referenceAnswer: "请替换为真实反馈案例。回答时先说明哪类用户在什么任务中反馈了什么，再解释你如何区分用户提出的方案和背后的问题；最后交代实际改动、没有做的部分，以及你如何回到同类用户验证结果。若只有单一反馈，要明确它仍是假设。",
        sourceRefs: ["S1-12"],
        followUps: [{ id: "tencent-feedback-iteration-f1", triggerLabel: "收到什么就做什么", requires: ["judgment"], question: "为什么没有照用户原话改？", answerFramework: ["区分诉求和问题", "验证共性", "解释最终取舍"], referenceAnswer: "用户给出的通常是一种解法。我会先还原他真正要完成的任务，再看同类反馈和行为证据，确认根因后才选方案。请补入你的真实取舍：哪些诉求被吸收、哪些没有做，以及原因是什么。" }],
        evaluationDimensions: [{ name: "反馈抽象", lookFor: "不把原话直接变需求。" }, { name: "闭环验证", lookFor: "回到用户任务。" }],
      },
      {
        id: "tencent-role-boundary", moduleId: "M6", category: "角色认知", priority: 1,
        question: "你怎么理解产品经理和运营、开发的关系？",
        keywords: ["共同目标", "专业边界", "需求取舍", "技术判断", "验收"],
        signalGroups: { problem: { label: "协作问题", keywords: ["共同目标", "冲突"], required: true }, context: { label: "角色责任", keywords: ["运营", "开发", "产品"], required: true }, action: { label: "协作机制", keywords: ["对齐", "验收"], required: true }, judgment: { label: "决策边界", keywords: ["负责", "边界"], required: true } },
        answerFramework: ["先说共同对用户结果负责", "分别说明专业责任", "解释冲突时如何靠证据收敛", "明确产品不替专业角色拍板"],
        referenceAnswer: "三方共同对用户和业务结果负责，但责任不同：运营更接近使用场景和持续采用，开发对技术方案、质量和长期成本负责，产品负责把零散诉求收敛成值得解决的问题，明确范围、优先级和验收。发生冲突时先对齐目标和证据；产品不能替开发决定实现，也不能越过专业负责人定义业务口径。",
        sourceRefs: ["L05"],
        followUps: [{ id: "tencent-role-boundary-f1", triggerLabel: "默认产品经理说了算", requires: ["judgment"], question: "三方意见冲突时，最后谁说了算？", answerFramework: ["按决策类型分权", "明确最终责任人", "不确定时做可逆验证"], referenceAnswer: "不按职位统一裁决。用户价值和优先级由产品组织证据，技术风险由开发负责判断，专业口径由相应负责人确认；仍不确定时缩小范围做验证，并明确由谁接受剩余风险。" }],
        evaluationDimensions: [{ name: "角色边界", lookFor: "责任具体且不越权。" }, { name: "协作机制", lookFor: "以目标和证据推进。" }],
      },
      {
        id: "tencent-role-fit", moduleId: "M6", category: "个人适配", priority: 1,
        question: "你为什么适合做产品？你的短板是什么？",
        keywords: ["能力证据", "可迁移优势", "真实短板", "补足动作"],
        signalGroups: { context: { label: "能力背景", keywords: ["经历", "背景"], required: true }, action: { label: "适配证据", keywords: ["做过", "负责"], required: true }, judgment: { label: "自我判断", keywords: ["优势", "短板"], required: true }, reflection: { label: "成长动作", keywords: ["补足", "练习"], required: true } },
        answerFramework: ["用两项有证据的优势对应岗位", "说一个真实且可改善的短板", "给出正在采取的动作", "说明如何快速进入陌生业务"],
        referenceAnswer: "我的优势是能把业务问题拆成清晰对象和规则，也习惯用证据验证取舍；这两点都来自真实项目中的需求澄清、方案推进和复盘。短板是对部分前端体验和工程约束还不够深入，我会通过原型实践、和研发做前置评审、复盘失败案例来补齐。进入陌生业务时，我先画用户、流程、核心对象和关键指标，再用访谈与数据校正假设。",
        sourceRefs: ["S1-09", "S1-11", "S2-17"],
        followUps: [{ id: "tencent-role-fit-f1", triggerLabel: "短板包装成优点", requires: ["reflection"], question: "这个短板真实造成过什么影响？", answerFramework: ["具体场景和影响", "本人责任", "补足动作与进展"], referenceAnswer: "这里必须换成真实影响：短板曾让哪项任务变慢、返工或判断失准，你承担什么责任，后来用了什么方法改善。不要把\"追求完美\"之类的优点包装成短板，也不要声称尚未发生过的改进结果。" }],
        evaluationDimensions: [{ name: "自我认知", lookFor: "优缺点均有事实支撑。" }, { name: "学习能力", lookFor: "补足动作可执行。" }],
      },
      {
        id: "tencent-company-motivation", moduleId: "M7", category: "岗位动机", priority: 1,
        question: "为什么选择腾讯？你更想做哪类产品？",
        keywords: ["经历匹配", "产品观察", "方向选择", "验证假设"],
        signalGroups: { context: { label: "选择背景", keywords: ["经历", "方向"], required: true }, action: { label: "相关准备", keywords: ["体验", "研究"], required: false }, evidence: { label: "具体依据", keywords: ["产品", "场景"], required: true }, judgment: { label: "选择逻辑", keywords: ["因为", "更想"], required: true } },
        answerFramework: ["先讲个人经历与岗位问题的匹配", "用公开产品机制给出公司判断", "明确偏好方向及原因", "把外部观察标为待验证假设"],
        referenceAnswer: "我选择目标公司，首先因为岗位问题与我的能力主线匹配：我希望继续做复杂业务中的数据与 AI 产品。其次，从公开产品体验看，这里的许多场景同时涉及关系、身份、沟通和交易，产品需要在便利、信任和生态协同之间长期取舍。这个判断来自外部观察，我会在交流中继续验证，而不是把它当作内部事实。",
        sourceRefs: ["L06", "L12"],
        followUps: [{ id: "tencent-company-motivation-f1", triggerLabel: "答案停在品牌和平台", requires: ["evidence", "judgment"], question: "和其他大厂相比，你看到的产品逻辑差异是什么？", answerFramework: ["限定为个人观察", "用一个公开机制举例", "承认不同产品不能一概而论"], referenceAnswer: "我的观察是，依赖真实关系和身份的产品更需要关注低打扰、信任与长期生态，而不只是功能密度。我会用具体公开机制说明，也承认这不能概括所有产品；真正的团队目标和取舍仍需要进入岗位后验证。" }],
        evaluationDimensions: [{ name: "动机可信", lookFor: "经历与岗位问题匹配。" }, { name: "判断克制", lookFor: "不虚构内部战略。" }],
      },
      {
        id: "tencent-career-plan", moduleId: "M7", category: "职业规划", priority: 2,
        question: "未来三到五年，你想成长成什么样的产品经理？",
        keywords: ["近期能力", "完整责任", "长期方向", "业务结果"],
        signalGroups: { context: { label: "当前阶段", keywords: ["现在", "基础"], required: true }, action: { label: "成长路径", keywords: ["先", "再"], required: true }, evidence: { label: "阶段标准", keywords: ["独立负责", "结果"], required: true }, judgment: { label: "方向选择", keywords: ["方向", "原因"], required: true } },
        answerFramework: ["近期补齐完整项目能力", "中期承担一类用户与业务结果", "长期形成领域判断", "用能力和责任而非头衔描述"],
        referenceAnswer: "前一两年，我希望能独立负责一个从用户问题、方案设计、跨团队交付到数据复盘的完整模块，补足外部用户研究和复杂交付能力。三到五年，我希望能对一类数据或 AI 产品问题承担更完整的用户与业务结果，并建立对质量、成本、权限和商业价值的系统判断。",
        sourceRefs: ["L07", "S2-13"],
        followUps: [{ id: "tencent-career-plan-f1", triggerLabel: "规划只有头衔或管理人数", requires: ["action", "evidence"], question: "你怎么判断自己到了下一阶段？", answerFramework: ["定义独立责任范围", "给出结果标准", "说明反馈来源"], referenceAnswer: "我会看自己能否独立定义问题、组织取舍、推动交付，并对上线后的结果负责；也会看是否能让团队复用一套有效方法，而不是只完成更多任务或获得一个新头衔。" }],
        evaluationDimensions: [{ name: "阶段清晰", lookFor: "成长路径可执行。" }, { name: "责任导向", lookFor: "不只谈职位。" }],
      },
      {
        id: "tencent-ai-product-design", moduleId: "M8", category: "AI 产品", priority: 1,
        question: "做一个垂类 AI 产品，你会怎么设计并验证？",
        keywords: ["用户任务", "AI 必要性", "技术路径", "MVP", "评测", "兜底"],
        signalGroups: { problem: { label: "任务问题", keywords: ["用户任务", "痛点"], required: true }, context: { label: "风险约束", keywords: ["风险", "权限"], required: true }, action: { label: "方案路径", keywords: ["基线", "MVP"], required: true }, evidence: { label: "评测证据", keywords: ["离线", "线上"], required: true }, judgment: { label: "AI 取舍", keywords: ["不用 AI", "选择"], required: true }, reflection: { label: "失败兜底", keywords: ["澄清", "人工"], required: true } },
        answerFramework: ["先拆具体任务与错误后果", "用最简单方案建立基线", "再决定检索、工具或模型增强", "用离线、线上和人工复核闭环验证"],
        referenceAnswer: "我先定义一类用户、一个任务和可判断的成功标准，再确认 AI 是否比规则、搜索或模板更合适。MVP 只覆盖输入清晰、结果可核验的窄场景，先建立简单基线，再按错误来源增加检索或工具。上线前做分层评测，线上看任务完成和人工修订，同时设置严重错误、成本与延迟护栏；能力不足时澄清、停止或转人工。",
        sourceRefs: ["S2-08", "S2-10"],
        followUps: [
          { id: "tencent-ai-product-design-f1", triggerLabel: "默认必须用 AI", requires: ["judgment"], question: "为什么这里一定要用 AI？", answerFramework: ["比较非 AI 基线", "指出 AI 的不可替代部分", "给出退出条件"], referenceAnswer: "如果规则或搜索能稳定解决，我不会为了标签使用 AI。AI 只在输入表达复杂、需要理解非结构化信息或个性化组织时可能更有价值；若质量和成本不能超过简单基线，就退回确定性方案。" },
          { id: "tencent-ai-product-design-f2", triggerLabel: "只有理想流程，没有风险边界", requires: ["context", "reflection"], question: "模型出错时产品怎么兜底？", answerFramework: ["按后果分风险", "不同等级设置确认和权限", "记录、撤销与回流"], referenceAnswer: "低风险内容允许生成后编辑，关键事实必须提供来源，高影响动作需要权限校验、预览和二次确认。能力不足时应明确说不知道或转人工，并保留审计、撤销和坏案例回流。" },
        ],
        evaluationDimensions: [{ name: "任务建模", lookFor: "先定义问题再选技术。" }, { name: "安全可控", lookFor: "有分级兜底。" }],
      },
      {
        id: "tencent-ai-skill-mcp", moduleId: "M8", category: "AI 产品", priority: 2,
        question: "你怎么理解 Skill 和 MCP 的区别？",
        keywords: ["任务方法", "工具协议", "输入输出", "组合关系", "边界"],
        signalGroups: { problem: { label: "概念问题", keywords: ["区别", "解决"], required: true }, context: { label: "适用场景", keywords: ["任务", "工具"], required: true }, action: { label: "组合方式", keywords: ["调用", "工作流"], required: true }, judgment: { label: "边界判断", keywords: ["不等于", "不一定"], required: true } },
        answerFramework: ["分别定义两者解决的问题", "说明可组合但不互相替代", "给一个公开通用例子", "不把未使用的技术说成项目事实"],
        referenceAnswer: "Skill 更像可复用的任务方法，说明何时触发、需要什么输入、经过哪些步骤、输出什么以及失败怎么办；MCP 是让模型用标准方式发现和连接外部工具或数据源的协议。MCP 告诉模型能调用什么，不等于定义怎样把任务做好；只处理已有上下文的 Skill 也不一定需要外部连接。",
        sourceRefs: ["L13"],
        followUps: [{ id: "tencent-ai-skill-mcp-f1", triggerLabel: "概念正确但没有场景", requires: ["context", "action"], question: "举个两者配合的例子。", answerFramework: ["选一个公开任务", "Skill 定义步骤", "MCP 提供外部能力", "说明权限和失败处理"], referenceAnswer: "例如做公开资料调研，Skill 可以规定拆题、检索、核验和引用的步骤；MCP 可以连接获准使用的搜索或文档工具。Skill 负责方法，协议负责连接，执行前仍要检查权限，工具失败时回退到可解释状态。" }],
        evaluationDimensions: [{ name: "概念准确", lookFor: "方法与连接协议分清。" }, { name: "边界诚实", lookFor: "不虚构项目使用。" }],
      },
      {
        id: "tencent-ai-evaluation", moduleId: "M8", category: "AI 评测", priority: 1,
        question: "论文 PDF 总结这类产品，评测体系怎么搭？",
        keywords: ["任务分层", "事实忠实", "引用", "覆盖", "鲁棒性", "对照"],
        signalGroups: { problem: { label: "质量定义", keywords: ["忠实", "引用"], required: true }, context: { label: "任务分层", keywords: ["浏览", "综述", "抽取"], required: true }, action: { label: "评测设计", keywords: ["测试集", "盲评"], required: true }, evidence: { label: "对照证据", keywords: ["基线", "修订"], required: true }, judgment: { label: "权重取舍", keywords: ["不同标准", "底线"], required: true } },
        answerFramework: ["按浏览、抽取、比较等任务分层", "设事实、引用、覆盖和可用性公共底线", "覆盖长文、表格、扫描和边界样本", "同条件比较基线并回流坏案例"],
        referenceAnswer: "我会先按任务分层：快速浏览看核心结论覆盖与耗时，事实抽取看字段准确和漏召，综述看主题组织、去重与引用。公共底线是不能捏造且关键结论可回到原文。测试集要覆盖长文、表格公式、扫描页和不同诉求，并在同一输入与盲评规则下比较简单基线、替代方案和人工修订成本。",
        sourceRefs: ["S2-07", "S2-09", "S2-11"],
        followUps: [
          { id: "tencent-ai-evaluation-f1", triggerLabel: "所有用户只用一个总分", requires: ["context", "judgment"], question: "不同用户诉求为什么不能用同一套权重？", answerFramework: ["公共底线", "任务差异", "分层权重"], referenceAnswer: "事实忠实和来源可追溯是公共底线，但快速判断是否值得读、精确抽取事实和形成综述的目标不同。应保留公共门槛，再按任务分别提高覆盖、字段准确或组织质量的权重。" },
          { id: "tencent-ai-evaluation-f2", triggerLabel: "把收藏量当成总结价值", requires: ["evidence"], question: "AI 总结和收藏到底解决什么？", answerFramework: ["还原收藏后的任务", "设计保存到复用闭环", "用后续行为验证"], referenceAnswer: "真正问题常是保存后找不到、忘了为什么保存，也无法继续使用。最小闭环是保留来源、生成可修改的主题和摘要，之后能按问题找回并转成笔记或任务；价值看后续检索和复用，而不是只看收藏次数。" },
        ],
        evaluationDimensions: [{ name: "评测分层", lookFor: "标准与任务匹配。" }, { name: "基线意识", lookFor: "公平对照且包含成本。" }],
      },
      {
        id: "tencent-favorite-product", moduleId: "M9", category: "产品感", priority: 1,
        question: "最近有什么产品是你真的喜欢用的？为什么？",
        keywords: ["真实场景", "核心机制", "替代方案", "短板", "改进"],
        signalGroups: { problem: { label: "原有阻力", keywords: ["原来", "问题"], required: true }, context: { label: "真实使用", keywords: ["任务", "频率"], required: true }, action: { label: "产品机制", keywords: ["流程", "反馈"], required: true }, evidence: { label: "体验证据", keywords: ["持续", "对比"], required: true }, judgment: { label: "产品判断", keywords: ["好在", "短板"], required: true } },
        answerFramework: ["说清真实使用任务", "拆出让体验成立的关键机制", "与替代方案比较", "主动指出副作用或短板"],
        referenceAnswer: "我会选一款自己持续用于资料整理的公开产品。它真正做得好的是让收集、理解和再次查找形成一条短链路，而不只是功能多。相比手动文件夹，它降低了整理负担；但自动组织也可能让用户失去控制。我会保留可追溯来源和手动修正入口，并关注复用价值与额外打扰。",
        sourceRefs: ["L18", "L19", "L20", "S1-08"],
        followUps: [
          { id: "tencent-favorite-product-f1", triggerLabel: "只夸功能，没有机制分析", requires: ["action", "judgment"], question: "哪一个设计最体现产品思维？", answerFramework: ["具体用户任务", "关键机制和取舍", "副作用"], referenceAnswer: "我会选一个能降低关键步骤成本、同时保护用户信任的公开机制，说明它服务谁、为什么这样设计、牺牲了什么，以及如果场景变化可能不再成立，而不是用“克制”或“生态”概括。" },
          { id: "tencent-favorite-product-f2", triggerLabel: "趋势判断只有热点名词", requires: ["judgment"], question: "最近你关注什么互联网或 AI 趋势？", answerFramework: ["描述趋势变化", "说明驱动因素", "分析对产品的影响与风险"], referenceAnswer: "我关注 AI 从生成答案进入可信工作流：开始读取获准数据、调用工具并执行动作。机会是让过去难以规模化的任务变得可用，风险则是权限、错误后果和责任边界同步放大，所以产品竞争会越来越依赖数据治理、评测和可恢复性。" },
          { id: "tencent-favorite-product-f3", triggerLabel: "无法解释热点产品增长", requires: ["context", "evidence"], question: "一款 AI 产品突然爆发，你会怎么分析原因？", answerFramework: ["能力阈值", "成本与门槛", "生态与传播", "长期验证"], referenceAnswer: "我会分四层看：能力是否达到用户可感知阈值，成本和使用门槛是否下降，开放生态是否促进分发和二次开发，以及时点与传播是否形成放大。短期爆发不等于长期优势，还要看真实任务效果、稳定性、留存和商业可持续性。" },
        ],
        evaluationDimensions: [{ name: "真实体验", lookFor: "有具体任务而非榜单观点。" }, { name: "机制分析", lookFor: "能解释价值与代价。" }],
      },
      {
        id: "tencent-journal-product", moduleId: "M9", category: "场景设计", priority: 2,
        question: "你平时怎么复盘？如果做一款记录产品，会怎么设计？",
        keywords: ["真实习惯", "记录时刻", "回看价值", "最小闭环", "隐私"],
        signalGroups: { problem: { label: "未满足痛点", keywords: ["忘记", "难找"], required: true }, context: { label: "真实习惯", keywords: ["场景", "频率"], required: true }, action: { label: "最小闭环", keywords: ["记录", "确认", "回看"], required: true }, evidence: { label: "验证方式", keywords: ["复用", "持续"], required: true }, judgment: { label: "AI 边界", keywords: ["不编造", "隐私"], required: true } },
        answerFramework: ["诚实说明现有习惯", "聚焦一个记录时刻和一类用户", "设计捕捉、确认、回看闭环", "说明 AI 与隐私边界"],
        referenceAnswer: "我的复盘更像在任务结束后记录关键判断和下一步，而不是每天写长日记。痛点是素材分散，回看时缺少当时语境。产品一期只服务项目复盘：导入零散材料，生成可修改草稿，用户确认后按问题、决策和行动保存，并在下次相似任务中提示。AI 不能编造情绪或记忆，敏感内容默认私密且可删除。",
        sourceRefs: ["S2-02", "S2-03", "S2-04", "S2-05", "S1-10", "S2-14"],
        followUps: [
          { id: "tencent-journal-product-f1", triggerLabel: "设计成全能记录工具", requires: ["problem", "action"], question: "一期只保留一个闭环，你留什么？", answerFramework: ["一个用户与时刻", "最短价值链", "主动删减"], referenceAnswer: "只保留任务结束后的快速复盘：收集少量素材、生成候选结构、用户确认、下次相似任务能找回。社交、复杂成长体系和全渠道自动采集先不做，先验证记录是否真的被再次使用。" },
          { id: "tencent-journal-product-f2", triggerLabel: "AI 自动生成用户人生叙事", requires: ["judgment"], question: "AI 怎么让记录更轻松但不越界？", answerFramework: ["辅助整理而非代写事实", "保留来源和修改权", "默认私密和可删除"], referenceAnswer: "AI 可以转写、归类和提出一两个追问，但不替用户编造感受。草稿必须可修改并保留原始材料，长期记忆由用户主动开启，内容可查看、导出和删除。" },
        ],
        evaluationDimensions: [{ name: "场景聚焦", lookFor: "一期用户和时刻明确。" }, { name: "隐私边界", lookFor: "用户保有控制权。" }],
      },
      {
        id: "tencent-payment-experience", moduleId: "M10", category: "支付场景", priority: 1,
        question: "如果负责微信支付的一次改版，你先解决什么问题？",
        keywords: ["支付前中后", "痛点证据", "关键链路", "确定性", "护栏"],
        signalGroups: { problem: { label: "体验问题", keywords: ["支付前", "支付后"], required: true }, context: { label: "用户场景", keywords: ["用户", "场景"], required: true }, action: { label: "最小方案", keywords: ["先改", "方案"], required: true }, evidence: { label: "验证信号", keywords: ["成功", "投诉"], required: true }, judgment: { label: "安全取舍", keywords: ["风险", "确定性"], required: true } },
        answerFramework: ["限定用户与支付阶段", "把个人观察标为待验证假设", "给出最小改动", "同时定义体验和安全护栏"],
        referenceAnswer: "我会先聚焦支付后找账单和理解交易信息的场景。假设是用户在退款、报销或核对消费时难以快速定位记录，但这需要用客服问题、任务测试和行为数据验证。若成立，我会先优化检索和交易信息解释，不改动付款主链路。验证任务解决情况，同时关注时延、误导、投诉和隐私风险。",
        sourceRefs: ["L21", "S2-15"],
        followUps: [
          { id: "tencent-payment-experience-f1", triggerLabel: "为了 AI 而 AI", requires: ["judgment"], question: "支付里哪些场景适合 AI？", answerFramework: ["选信息复杂但动作可控的环节", "AI 负责解释建议", "交易动作仍由确定性系统控制"], referenceAnswer: "适合的是账单解释、商家经营异常归纳或客服辅助等信息复杂但执行可控的环节。AI 可以帮助理解和建议，关键事实必须有来源；付款、账户和风控决定继续由确定性系统控制并经过权限确认。" },
          { id: "tencent-payment-experience-f2", triggerLabel: "只看体验收益", requires: ["evidence", "judgment"], question: "怎么验证又不影响支付安全？", answerFramework: ["先离线高风险评测", "小流量只读灰度", "同时观察任务指标和安全护栏"], referenceAnswer: "先离线验证事实准确、意图识别和高风险错误，再以只读、可退出的小流量方式灰度。线上看问题是否解决和转人工情况，同时把错误建议、支付成功、时延、投诉与隐私事件作为停止护栏。" },
        ],
        evaluationDimensions: [{ name: "场景具体", lookFor: "明确用户和步骤。" }, { name: "风险意识", lookFor: "交易确定性优先。" }],
      },
      {
        id: "tencent-qr-ordering", moduleId: "M10", category: "角色扮演", priority: 2,
        question: "用二十秒向一位没用过的餐饮商家介绍扫码点餐。",
        keywords: ["商家语言", "核心价值", "高峰期", "低门槛", "本地适配"],
        signalGroups: { problem: { label: "商家痛点", keywords: ["排队", "错单"], required: true }, context: { label: "使用场景", keywords: ["顾客", "后厨"], required: true }, action: { label: "产品链路", keywords: ["扫码", "下单"], required: true }, evidence: { label: "业务价值", keywords: ["减少", "看到"], required: true }, judgment: { label: "落地边界", keywords: ["试用", "兜底"], required: false } },
        answerFramework: ["先说顾客如何使用", "再说商家直接收益", "最后降低迁移顾虑", "不用技术术语"],
        referenceAnswer: "顾客扫码就能看菜单、自己下单和付款，订单直接同步到门店处理。高峰期能减少排队、错单和重复沟通，您也更容易看清哪些菜受欢迎。可以先从少量桌台试用，我们会协助配置，不需要一次改变全部经营流程。",
        sourceRefs: ["S2-16"],
        followUps: [
          { id: "tencent-qr-ordering-f1", triggerLabel: "只强调先进，没有回应顾虑", requires: ["judgment"], question: "商家担心员工不会用、网络不稳定，怎么办？", answerFramework: ["小范围试用", "培训和人工兜底", "弱网与异常处理", "按本地习惯适配"], referenceAnswer: "先在少量桌台试用，提供现场引导并保留人工点单。弱网时保障已加载菜单和订单状态可确认，异常订单由员工处理；语言、支付和合规按当地情况适配，再用高峰期任务表现决定是否扩大。" },
        ],
        evaluationDimensions: [{ name: "价值表达", lookFor: "商家能迅速理解收益。" }, { name: "落地可行", lookFor: "考虑迁移和本地约束。" }],
      },
      {
        id: "tencent-priority-value", moduleId: "M11", category: "优先级与数据", priority: 1,
        question: "权限问题、导入失败、AI 新需求和体验优化同时出现，你怎么排？",
        keywords: ["安全底线", "核心任务", "影响范围", "证据强度", "商业价值", "验证"],
        signalGroups: { problem: { label: "问题分级", keywords: ["权限", "阻断"], required: true }, context: { label: "影响语境", keywords: ["用户范围", "频率"], required: true }, action: { label: "排序动作", keywords: ["止损", "排期"], required: true }, evidence: { label: "验证方式", keywords: ["过程", "结果", "护栏"], required: true }, judgment: { label: "价值取舍", keywords: ["底线", "成本"], required: true } },
        answerFramework: ["先处理安全、正确性和核心阻断", "再比较影响、频率、价值、确定性和成本", "写清延期代价与复查点", "用过程、结果和护栏验证"],
        referenceAnswer: "我不会把四项直接塞进一个分数。若权限问题可能越权，先止损；若导入失败阻断核心任务，紧接着恢复主链路。底线稳定后，再比较 AI 新需求与体验优化的目标用户、发生频率、证据强度和成本。排完会写清延期代价、负责人和复查节点，并用任务结果而非上线数量验证。",
        sourceRefs: ["S1-03", "S1-05", "S1-07"],
        followUps: [
          { id: "tencent-priority-value-f1", triggerLabel: "只背排序公式", requires: ["context", "judgment"], question: "用户价值和商业价值冲突时怎么办？", answerFramework: ["区分用户、付费者和成本承担者", "守住安全与信任底线", "比较长期价值和可逆性"], referenceAnswer: "先分清谁使用、谁付费、谁受益、谁承担成本。安全和信任不能拿来交换短期收益；底线之上，再比较长期用户价值、交付维护成本和方案可逆性，必要时通过分层、套餐或灰度寻找平衡。" },
          { id: "tencent-priority-value-f2", triggerLabel: "上线就算完成", requires: ["evidence"], question: "你会怎么用数据验证优化有效？", answerFramework: ["定义要改变的用户行为", "过程、结果、护栏三层指标", "选择合理对照"], referenceAnswer: "先定义功能要改变的具体行为。过程看用户能否完成关键步骤，结果看任务质量、耗时或持续使用，护栏看错误、投诉和维护成本；条件允许时做对照或分阶段开放，并说明样本和周期限制。" },
          { id: "tencent-priority-value-f3", triggerLabel: "遇到上级分歧只服从或硬顶", requires: ["action", "judgment"], question: "负责人和你判断不一样呢？", answerFramework: ["确认共同目标", "还原分歧假设和代价", "提出小范围验证", "明确升级底线"], referenceAnswer: "我先确认目标是否一致，再把分歧还原为假设、证据和代价，提出可逆的小范围验证。最终决策后认真执行并保留监控；若涉及安全、合规或严重数据风险，则明确升级，不把底线当普通偏好。" },
        ],
        evaluationDimensions: [{ name: "优先级纪律", lookFor: "先底线后价值。" }, { name: "数据闭环", lookFor: "结果与护栏并重。" }],
      },
      {
        id: "tencent-reverse", moduleId: "M12", category: "反问", priority: 0, maxFollowUps: 0, evaluationProfile: "reverse-question",
        question: "你有什么想问我的吗？",
        keywords: ["团队目标", "成功标准", "岗位期待", "当前挑战"],
        signalGroups: { context: { label: "本场关联", keywords: ["刚才", "提到"], required: false }, action: { label: "具体问题", keywords: ["如何判断", "期待"], required: true }, judgment: { label: "双向匹配", keywords: ["优先", "挑战"], required: true } },
        answerFramework: ["先承接本场聊过的关键词", "优先问团队正在判断的问题、成功标准或岗位期待", "现场选两到三个问题", "根据回答追问原因、信号或协作方式"],
        referenceAnswer: "有的。刚才您提到团队正在推进一项重要能力，我想进一步了解：未来半年最优先解决的用户问题是什么，目前最大的未确定性在哪里？另外，对于这个岗位，您会怎样判断一位新人已经进入状态？如果您提到某项挑战，我会接着问：它更主要来自用户习惯、底层能力还是跨团队协作，团队会用什么信号判断正在改善？",
        sourceRefs: ["L08"], followUps: [],
        evaluationDimensions: [{ name: "信息增量", lookFor: "问题无法靠公开搜索直接回答。" }, { name: "岗位关联", lookFor: "能帮助双向判断匹配。" }, { name: "自然追问", lookFor: "能承接对方回答继续问。" }],
      },
    ],
  },
];

if (typeof window !== "undefined") {
  window.MOCK_QUESTION_PACKS = MOCK_QUESTION_PACKS;
}

if (typeof module !== "undefined" && module.exports) {
  module.exports = MOCK_QUESTION_PACKS;
}
