/**
 * Public mock-interview question packs.
 *
 * This file intentionally uses a classic script global instead of ES modules so it
 * can be loaded directly with a <script> tag. The CommonJS export keeps the same
 * data available to local validation and test tooling.
 */
var MOCK_QUESTION_PACKS = [
  {
    id: "wecom-smart-sheet-pm",
    title: "企业微信智能表格 · 产品经理",
    description:
      "面向企业协作与智能表格产品经理岗位的公开模拟题库，重点考察产品判断、AI 方案、企业级治理与落地能力。请基于公开信息或脱敏案例作答；本题库不代表任何公司的官方招聘标准或产品路线。",
    competencies: [
      "经历迁移与产品理解",
      "用户问题与需求抽象",
      "企业产品与平台判断",
      "AI 产品设计与评测",
      "数据权限与安全治理",
      "跨团队推进与复盘",
    ],
    version: "2.0.0",
    interviewFlow: {
      15: [
        "wecom-introduction",
        "wecom-flagship-project",
        "wecom-positioning",
        "wecom-ai-feature",
      ],
      30: [
        "wecom-introduction",
        "wecom-flagship-project",
        "wecom-method-transfer",
        "wecom-positioning",
        "wecom-ai-feature",
      ],
      45: [
        "wecom-introduction",
        "wecom-flagship-project",
        "wecom-method-transfer",
        "wecom-demand-abstraction",
        "wecom-positioning",
        "wecom-ai-feature",
        "wecom-ai-value",
        "wecom-disagreement",
      ],
    },
    questions: [
      {
        id: "wecom-introduction",
        category: "开场",
        priority: 0,
        maxFollowUps: 0,
        evaluationProfile: "introduction",
        question: "先简单介绍一下自己吧。",
        keywords: ["经历主线", "当前方向", "代表项目", "核心能力"],
        signalGroups: {
          context: { label: "个人背景", keywords: ["硕士", "本科", "专业", "实习", "经历"], required: true },
          action: { label: "经历主线", keywords: ["负责", "参与", "产品", "分析", "项目"], required: true },
          judgment: { label: "能力定位", keywords: ["擅长", "优势", "能力", "关注", "主线"], required: true },
        },
        followUps: [],
        evaluationDimensions: [
          { name: "信息取舍", lookFor: "在一分钟内交代背景、代表经历和能力主线。" },
          { name: "个人定位", lookFor: "让面试官知道后续最值得追问什么。" },
          { name: "表达自然度", lookFor: "口语化表达，不逐条复述简历。" },
        ],
      },
      {
        id: "wecom-method-transfer",
        category: "项目深挖",
        priority: 1,
        question: "你刚才这个项目里，哪些事情原来主要靠人工或经验？后来是怎么把它做成产品能力的？",
        keywords: ["业务问题", "知识结构化", "规则抽象", "产品化", "可配置", "复用验证"],
        signalGroups: {
          problem: { label: "原始问题", keywords: ["信息分散", "人工成本", "标准不一", "协作低效"], required: true },
          context: { label: "用户与约束", keywords: ["使用角色", "业务场景", "原有流程", "约束"], required: true },
          action: { label: "产品化过程", keywords: ["梳理", "抽象", "结构化", "配置", "上线"], required: true },
          evidence: { label: "复用证据", keywords: ["覆盖范围", "使用反馈", "效率", "准确率", "持续使用"], required: true },
          judgment: { label: "抽象取舍", keywords: ["共性与个性", "产品边界", "优先级", "治理"], required: true },
          reflection: { label: "迭代复盘", keywords: ["问题", "迭代", "可迁移方法", "下一步"], required: false },
        },
        followUps: [
          { id: "wecom-method-transfer-f1", triggerLabel: "直接罗列功能，没有还原产品化前的问题", requires: ["problem", "context"], question: "为什么当时不能继续靠人工或者文档来解决？" },
          { id: "wecom-method-transfer-f2", triggerLabel: "只讲整理过程，没有说明抽象和取舍", requires: ["action", "judgment"], question: "这里面哪些做成了统一规则，哪些保留了业务差异？" },
          { id: "wecom-method-transfer-f3", triggerLabel: "把交付完成当作产品有效", requires: ["evidence", "reflection"], question: "你怎么确认它真的改善了原来的流程？" },
        ],
        evaluationDimensions: [
          { name: "问题还原", lookFor: "说明产品化前的用户、流程、成本与核心矛盾。" },
          { name: "抽象能力", lookFor: "能从具体需求中拆出稳定共性与可配置差异。" },
          { name: "产品闭环", lookFor: "完整说明结构设计、协作推进、上线使用与治理机制。" },
          { name: "结果可信度", lookFor: "用覆盖、效率、质量或持续使用证据验证复用价值。" },
        ],
      },
      {
        id: "wecom-positioning",
        category: "产品判断",
        priority: 1,
        question: "你怎么理解企业微信智能表格？它主要在解决什么问题？",
        keywords: ["结构化记录", "轻量业务应用", "协作执行", "多角色", "产品边界", "价值闭环"],
        signalGroups: {
          problem: { label: "核心任务", keywords: ["记录管理", "流程协同", "动作闭环"], required: true },
          context: { label: "用户与场景", keywords: ["搭建者", "一线执行者", "管理者"], required: true },
          action: { label: "产品机制", keywords: ["字段与视图", "权限", "自动化"], required: true },
          evidence: { label: "验证信号", keywords: ["首次闭环", "持续更新", "组织留存"], required: false },
          judgment: { label: "定位边界", keywords: ["适用范围", "不替代", "差异化假设"], required: true },
          reflection: { label: "不确定性", keywords: ["公开信息边界", "待验证假设", "反例"], required: false },
        },
        followUps: [
          { id: "wecom-positioning-f1", triggerLabel: "把产品等同于带 AI 的传统表格", requires: ["problem", "action"], question: "那它和 Excel、普通在线表格最大的区别是什么？" },
          { id: "wecom-positioning-f2", triggerLabel: "声称能替代所有专业系统", requires: ["judgment", "reflection"], question: "哪些事情你觉得它并不适合做？" },
          { id: "wecom-positioning-f3", triggerLabel: "只有概念，缺少多角色和验证方式", requires: ["context", "evidence"], question: "谁会最先用它？为什么会持续用下去？" },
        ],
        evaluationDimensions: [
          { name: "定位清晰度", lookFor: "用用户任务和工作流定义产品，不堆叠空泛标签。" },
          { name: "多角色视角", lookFor: "同时考虑配置、执行、管理与治理角色的价值和成本。" },
          { name: "边界判断", lookFor: "能区分灵活协作流程与重型专业系统。" },
          { name: "验证意识", lookFor: "用真实闭环与持续采用验证定位，而非只看建表量。" },
        ],
      },
      {
        id: "wecom-flagship-project",
        category: "项目深挖",
        priority: 1,
        question: "挑一个你做得最深入的项目讲讲。",
        keywords: ["问题定义", "个人贡献", "关键取舍", "协同交付", "结果证据", "复盘"],
        signalGroups: {
          problem: { label: "问题定义", keywords: ["目标用户", "核心痛点", "为什么值得做"], required: true },
          context: { label: "约束背景", keywords: ["旧方案", "资源约束", "成功标准"], required: true },
          action: { label: "个人行动", keywords: ["本人决策", "方案推进", "交付验收"], required: true },
          evidence: { label: "结果证据", keywords: ["口径说明", "用户行为", "可信结果"], required: true },
          judgment: { label: "关键取舍", keywords: ["备选方案", "优先级", "风险权衡"], required: true },
          reflection: { label: "复盘迁移", keywords: ["未达预期", "机制改进", "可迁移方法"], required: true },
        },
        followUps: [
          { id: "wecom-flagship-project-f1", triggerLabel: "罗列功能，没有收敛核心问题", requires: ["problem", "context"], question: "这个项目一开始为什么要做？最核心的问题是什么？" },
          { id: "wecom-flagship-project-f2", triggerLabel: "大量使用“我们”，个人边界不清", requires: ["action", "judgment"], question: "你在里面具体负责哪一部分？有哪个关键判断是你做的？" },
          { id: "wecom-flagship-project-f3", triggerLabel: "结果缺少口径或只报正向结论", requires: ["evidence", "reflection"], question: "最后怎么判断它做得好不好？有没有没达到预期的地方？" },
        ],
        evaluationDimensions: [
          { name: "结构表达", lookFor: "完整串联问题、约束、行动、结果和复盘。" },
          { name: "所有权边界", lookFor: "清楚区分个人贡献、团队成果与专业角色责任。" },
          { name: "决策质量", lookFor: "呈现真实备选方案、证据和取舍。" },
          { name: "结果可信度", lookFor: "解释指标口径和未知边界，不编造或夸大。" },
        ],
      },
      {
        id: "wecom-demand-abstraction",
        category: "用户与需求",
        priority: 1,
        question: "业务方只说‘想用表格把这件事管起来’，你会先问什么？",
        keywords: ["用户任务", "业务对象", "字段关系", "角色权限", "自动化", "验收标准"],
        signalGroups: {
          problem: { label: "需求本质", keywords: ["目标动作", "现有阻碍", "使用频率"], required: true },
          context: { label: "业务模型", keywords: ["对象关系", "角色", "状态流转"], required: true },
          action: { label: "方案映射", keywords: ["字段视图", "权限规则", "触发动作"], required: true },
          evidence: { label: "验收证据", keywords: ["任务样例", "异常状态", "完成指标"], required: true },
          judgment: { label: "抽象取舍", keywords: ["通用与定制", "一期边界", "维护成本"], required: true },
          reflection: { label: "迭代机制", keywords: ["反馈回流", "配置摩擦", "扩展条件"], required: false },
        },
        followUps: [
          { id: "wecom-demand-abstraction-f1", triggerLabel: "按用户原话直接堆功能", requires: ["problem", "context"], question: "谁在用？现在是怎么做的？最卡的是哪一步？" },
          { id: "wecom-demand-abstraction-f2", triggerLabel: "方案过度定制或过度通用", requires: ["action", "judgment"], question: "如果一期只能解决一个问题，你先做什么？" },
          { id: "wecom-demand-abstraction-f3", triggerLabel: "把搭建完成当作验收完成", requires: ["evidence", "reflection"], question: "上线后你怎么判断这个需求真的解决了？" },
        ],
        evaluationDimensions: [
          { name: "需求抽象", lookFor: "把口头诉求还原为业务对象、角色、状态和动作。" },
          { name: "方案完整性", lookFor: "覆盖数据结构、视图、权限、自动化与异常状态。" },
          { name: "平台取舍", lookFor: "平衡通用能力、场景模板和个性配置。" },
          { name: "任务验收", lookFor: "以真实任务改善而非页面交付作为成功标准。" },
        ],
      },
      {
        id: "wecom-competitive-differentiation",
        category: "产品判断",
        priority: 2,
        question: "飞书多维表格、钉钉 AI 表格已经比较成熟了，你觉得企微的机会在哪？",
        keywords: ["目标场景", "原生协作", "迁移成本", "能力门槛", "竞争假设", "验证指标"],
        signalGroups: {
          problem: { label: "竞争问题", keywords: ["用户为何切换", "替代成本", "同质化"], required: true },
          context: { label: "竞争语境", keywords: ["用户存量工具", "组织协作", "生态约束"], required: true },
          action: { label: "验证方案", keywords: ["同场景对比", "局部迁移", "小范围试点"], required: true },
          evidence: { label: "差异证据", keywords: ["配置步骤", "闭环耗时", "可靠性"], required: true },
          judgment: { label: "竞争判断", keywords: ["基础门槛", "独特资产", "成立条件"], required: true },
          reflection: { label: "反例边界", keywords: ["优势不成立", "并存策略", "不强迫迁移"], required: true },
        },
        followUps: [
          { id: "wecom-competitive-differentiation-f1", triggerLabel: "只比较功能数量", requires: ["problem", "judgment"], question: "如果功能都差不多，用户为什么要换？" },
          { id: "wecom-competitive-differentiation-f2", triggerLabel: "把入口或关系网络直接当作壁垒", requires: ["evidence", "reflection"], question: "你怎么证明企微里的关系链真的能带来优势？" },
          { id: "wecom-competitive-differentiation-f3", triggerLabel: "默认用户会整体迁移", requires: ["context", "action"], question: "如果用户不愿意放弃现在的工具，你会怎么办？" },
        ],
        evaluationDimensions: [
          { name: "竞争框架", lookFor: "比较场景、链路与结果，不做功能清单或品牌站队。" },
          { name: "假设意识", lookFor: "把潜在优势视为需验证假设，并说明成立条件。" },
          { name: "用户成本", lookFor: "考虑学习、迁移、集成和组织切换成本。" },
          { name: "反证能力", lookFor: "能明确何种证据会否定原判断。" },
        ],
      },
      {
        id: "wecom-ai-feature",
        category: "AI 产品设计",
        priority: 1,
        question: "如果让你给智能表格加一个 AI 能力，你会先做什么？",
        keywords: ["窄场景", "用户任务", "结构化配置", "人机协作", "风险控制", "实验验证"],
        signalGroups: {
          problem: { label: "场景痛点", keywords: ["高频任务", "人工成本", "结果明确"], required: true },
          context: { label: "用户流程", keywords: ["输入来源", "使用角色", "下游动作"], required: true },
          action: { label: "产品方案", keywords: ["信息补齐", "生成预览", "确认执行"], required: true },
          evidence: { label: "实验证据", keywords: ["完成率", "耗时", "修改率"], required: true },
          judgment: { label: "MVP 取舍", keywords: ["一期范围", "不用 AI 的部分", "平台适配"], required: true },
          reflection: { label: "风险边界", keywords: ["错误后果", "人工兜底", "回滚"], required: true },
        },
        followUps: [
          { id: "wecom-ai-feature-f1", triggerLabel: "设计成泛化聊天框，缺少具体任务", requires: ["problem", "context"], question: "这个需求是谁在什么环节遇到的？" },
          { id: "wecom-ai-feature-f2", triggerLabel: "一期范围过大或没有方案取舍", requires: ["action", "judgment"], question: "一期只能做得很小，你会保留什么？" },
          { id: "wecom-ai-feature-f3", triggerLabel: "默认 AI 可直接写入或外发", requires: ["evidence", "reflection"], question: "AI 做错了会怎样？哪些动作不能让它直接做？" },
        ],
        evaluationDimensions: [
          { name: "场景选择", lookFor: "选择高频、结果可判定且适合结构化数据的任务。" },
          { name: "方案闭环", lookFor: "覆盖输入、处理、预览、执行、异常和结果回填。" },
          { name: "MVP 取舍", lookFor: "明确一期边界和非 AI 更合适的部分。" },
          { name: "安全可控", lookFor: "按风险设置确认、审计、人工兜底与回滚。" },
          { name: "验证设计", lookFor: "比较原流程与新流程的任务结果，而非只看调用。" },
        ],
      },
      {
        id: "wecom-ai-value",
        category: "指标与实验",
        priority: 1,
        question: "这个 AI 功能上线以后，你会看哪些数据判断它有没有用？",
        keywords: ["真实激活", "输出质量", "下游动作", "持续使用", "业务结果", "护栏指标"],
        signalGroups: {
          problem: { label: "价值问题", keywords: ["目标任务", "原流程基线", "用户成本"], required: true },
          context: { label: "任务周期", keywords: ["使用频率", "角色差异", "样本条件"], required: true },
          action: { label: "验证设计", keywords: ["对照", "分阶段开放", "质量抽检"], required: true },
          evidence: { label: "指标链条", keywords: ["完成率", "修改率", "下游动作", "留存"], required: true },
          judgment: { label: "因果判断", keywords: ["虚荣指标", "选择偏差", "任务归因"], required: true },
          reflection: { label: "护栏复盘", keywords: ["严重错误", "延迟成本", "停止阈值"], required: true },
        },
        followUps: [
          { id: "wecom-ai-value-f1", triggerLabel: "只看调用量、人数或采纳率", requires: ["problem", "evidence"], question: "调用量很高，就一定说明有价值吗？" },
          { id: "wecom-ai-value-f2", triggerLabel: "忽略任务周期或用户差异", requires: ["context", "judgment"], question: "如果这个任务本来就很低频，你怎么衡量？" },
          { id: "wecom-ai-value-f3", triggerLabel: "没有因果验证与风险护栏", requires: ["action", "reflection"], question: "你怎么排除只是新鲜感或者用户本来就更积极？" },
        ],
        evaluationDimensions: [
          { name: "价值链条", lookFor: "从激活、质量、下游动作到持续结果逐层验证。" },
          { name: "指标质量", lookFor: "组合任务指标与护栏指标，不依赖单一虚荣指标。" },
          { name: "因果意识", lookFor: "识别样本偏差，并采用合理对照或阶段比较。" },
          { name: "周期匹配", lookFor: "指标周期符合任务真实发生频率。" },
        ],
      },
      {
        id: "wecom-cold-start",
        category: "增长与采用",
        priority: 1,
        question: "这类企业产品如果从零开始，你会先从什么场景切？",
        keywords: ["窄场景", "种子用户", "首次闭环", "高接触验证", "产品化沉淀", "组织留存"],
        signalGroups: {
          problem: { label: "切入痛点", keywords: ["高频流程", "明确损失", "角色完整"], required: true },
          context: { label: "种子条件", keywords: ["数据可用", "共创意愿", "决策链"], required: true },
          action: { label: "启动路径", keywords: ["陪跑", "模板", "迁移与引导"], required: true },
          evidence: { label: "采用证据", keywords: ["首次价值", "一线更新", "组织留存"], required: true },
          judgment: { label: "规模化判断", keywords: ["共性障碍", "人工与产品", "复制条件"], required: true },
          reflection: { label: "失活诊断", keywords: ["旧流程并存", "配置负担", "激励错位"], required: false },
        },
        followUps: [
          { id: "wecom-cold-start-f1", triggerLabel: "从万能空表或广泛获客开始", requires: ["problem", "context"], question: "第一批用户你会找谁？" },
          { id: "wecom-cold-start-f2", triggerLabel: "把开通、建表或导入当作激活", requires: ["action", "evidence"], question: "用户做到哪一步，才算真的用起来了？" },
          { id: "wecom-cold-start-f3", triggerLabel: "长期依赖人工实施，缺少规模化路径", requires: ["judgment", "reflection"], question: "前期可以靠人陪跑，后面怎么把它规模化？" },
        ],
        evaluationDimensions: [
          { name: "切入策略", lookFor: "从痛点强、角色清楚且能闭环的窄流程切入。" },
          { name: "激活定义", lookFor: "以真实数据进入、责任行动与结果回填定义首次价值。" },
          { name: "组织采用", lookFor: "关注不同角色行为和旧流程是否真正迁移。" },
          { name: "规模化路径", lookFor: "将高接触验证中的共性障碍沉淀为产品能力。" },
        ],
      },
      {
        id: "wecom-prioritization",
        category: "产品规划",
        priority: 1,
        question: "现在权限问题、导入失败、AI 新需求和界面优化同时来了，你怎么排？",
        keywords: ["信任底线", "用户价值", "影响范围", "证据置信度", "成本风险", "复盘"],
        signalGroups: {
          problem: { label: "问题分层", keywords: ["安全风险", "核心阻塞", "体验改善"], required: true },
          context: { label: "影响语境", keywords: ["用户范围", "发生频次", "商业与合规"], required: true },
          action: { label: "决策过程", keywords: ["证据收集", "技术评估", "资源编排"], required: true },
          evidence: { label: "排序证据", keywords: ["故障数据", "用户行为", "客户反馈"], required: true },
          judgment: { label: "优先级原则", keywords: ["底线优先", "价值风险", "战略一致"], required: true },
          reflection: { label: "结果复盘", keywords: ["复发率", "任务改善", "假设更新"], required: false },
        },
        followUps: [
          { id: "wecom-prioritization-f1", triggerLabel: "机械套用评分公式", requires: ["problem", "judgment"], question: "你先讲原则，再讲这四个具体会怎么排。" },
          { id: "wecom-prioritization-f2", triggerLabel: "只依赖单一声音或职位高低", requires: ["context", "evidence"], question: "如果老板最关心的和你的判断不一样，你怎么沟通？" },
          { id: "wecom-prioritization-f3", triggerLabel: "没有落地和复盘机制", requires: ["action", "reflection"], question: "排完以后，你怎么知道当时的判断是对的？" },
        ],
        evaluationDimensions: [
          { name: "分层原则", lookFor: "先守权限、安全、数据正确和稳定性底线。" },
          { name: "证据质量", lookFor: "综合行为、反馈、故障、商业与技术证据。" },
          { name: "取舍沟通", lookFor: "用共同目标、备选方案和代价说明优先级。" },
          { name: "复盘能力", lookFor: "上线后检验任务改善、风险变化与原假设。" },
        ],
      },
      {
        id: "wecom-ai-permissions",
        category: "安全与治理",
        priority: 1,
        question: "如果 AI 能读表、改表，甚至自动发消息，你最担心什么？",
        keywords: ["最小权限", "取数裁剪", "动作校验", "敏感数据", "审计", "回滚"],
        signalGroups: {
          problem: { label: "风险识别", keywords: ["越权读取", "越权推断", "错误执行"], required: true },
          context: { label: "权限语境", keywords: ["用户权限", "任务授权", "数据敏感级别"], required: true },
          action: { label: "控制机制", keywords: ["读取前裁剪", "二次校验", "预览确认"], required: true },
          evidence: { label: "治理证据", keywords: ["授权记录", "执行日志", "安全测试"], required: true },
          judgment: { label: "风险分级", keywords: ["可逆操作", "高风险动作", "人工确认"], required: true },
          reflection: { label: "对抗与恢复", keywords: ["恶意指令", "异常检测", "撤销回滚"], required: true },
        },
        followUps: [
          { id: "wecom-ai-permissions-f1", triggerLabel: "只说沿用用户权限，没有说明取数阶段", requires: ["context", "action"], question: "用户只能看一部分数据时，AI 最后能总结到什么程度？" },
          { id: "wecom-ai-permissions-f2", triggerLabel: "所有动作一律自动或一律确认", requires: ["judgment", "evidence"], question: "哪些动作可以自动做，哪些必须让人确认？" },
          { id: "wecom-ai-permissions-f3", triggerLabel: "忽略输入攻击、审计或恢复", requires: ["problem", "reflection"], question: "如果它批量做错了，怎么发现、怎么撤回？" },
        ],
        evaluationDimensions: [
          { name: "权限模型", lookFor: "AI 可见范围是用户权限与任务授权的交集，且取数前裁剪。" },
          { name: "动作安全", lookFor: "写入、外发和权限变更前重新校验并按风险确认。" },
          { name: "数据治理", lookFor: "考虑敏感级别、跨表聚合和间接推断风险。" },
          { name: "可审计恢复", lookFor: "保留授权、来源和执行日志，并具备撤销或回滚路径。" },
        ],
      },
      {
        id: "wecom-data-migration",
        category: "企业产品基础",
        priority: 2,
        question: "用户历史数据很乱，权限也不一致，你会怎么设计迁移？",
        keywords: ["数据盘点", "字段映射", "质量校验", "权限继承", "试迁移", "回退"],
        signalGroups: {
          problem: { label: "迁移风险", keywords: ["数据丢失", "口径冲突", "业务中断"], required: true },
          context: { label: "数据语境", keywords: ["来源类型", "数据规模", "角色权限"], required: true },
          action: { label: "迁移方案", keywords: ["字段映射", "预检查", "分批迁移"], required: true },
          evidence: { label: "验收证据", keywords: ["抽样核对", "差异报告", "业务验收"], required: true },
          judgment: { label: "取舍策略", keywords: ["自动与人工", "阻断条件", "兼容范围"], required: true },
          reflection: { label: "恢复与治理", keywords: ["回退", "持续同步", "数据责任人"], required: true },
        },
        followUps: [
          { id: "wecom-data-migration-f1", triggerLabel: "只描述上传文件，没有数据盘点", requires: ["problem", "context"], question: "迁移前你最先盘什么？" },
          { id: "wecom-data-migration-f2", triggerLabel: "假设字段可以自动一一对应", requires: ["action", "judgment"], question: "哪些能自动处理，哪些必须让客户确认？" },
          { id: "wecom-data-migration-f3", triggerLabel: "没有验收、失败恢复和并存计划", requires: ["evidence", "reflection"], question: "如果迁移中途失败了，怎么保证业务不受影响？" },
        ],
        evaluationDimensions: [
          { name: "风险完整性", lookFor: "识别数据、口径、权限、依赖与业务连续性风险。" },
          { name: "迁移流程", lookFor: "包含预检查、映射、试迁移、校验、切换与回退。" },
          { name: "人机分工", lookFor: "自动处理确定性规则，将歧义与高风险项交给责任人。" },
          { name: "业务验收", lookFor: "不仅检查行数，还验证关键任务与权限结果。" },
        ],
      },
      {
        id: "wecom-ai-evaluation",
        category: "AI 产品设计",
        priority: 1,
        question: "一个 AI 功能上线前，你会怎么判断它够不够好？",
        keywords: ["任务分类", "评测集", "业务预期", "过程证据", "人工复核", "回归测试"],
        signalGroups: {
          problem: { label: "质量目标", keywords: ["任务成功", "严重错误", "用户影响"], required: true },
          context: { label: "样本结构", keywords: ["典型任务", "边界样本", "风险分层"], required: true },
          action: { label: "评测闭环", keywords: ["离线评测", "线上反馈", "归因修复", "回归"], required: true },
          evidence: { label: "可核验信号", keywords: ["预期结果", "可观察日志", "人工抽检"], required: true },
          judgment: { label: "评判边界", keywords: ["多种合理答案", "人机分工", "发布门槛"], required: true },
          reflection: { label: "评测治理", keywords: ["样本漂移", "评审偏差", "版本追踪"], required: true },
        },
        followUps: [
          { id: "wecom-ai-evaluation-f1", triggerLabel: "只说准备问题和标准答案", requires: ["problem", "context"], question: "除了用户问题，一条评测样本里还要有什么？" },
          { id: "wecom-ai-evaluation-f2", triggerLabel: "把自动打分当作最终裁判", requires: ["evidence", "judgment"], question: "自动评测和人工判断冲突了，听谁的？" },
          { id: "wecom-ai-evaluation-f3", triggerLabel: "评测止于跑分，没有回流迭代", requires: ["action", "reflection"], question: "发现 Bad Case 以后，怎么保证不是只修这一条？" },
        ],
        evaluationDimensions: [
          { name: "评测设计", lookFor: "按任务与风险分层，定义可核验预期和边界样本。" },
          { name: "证据质量", lookFor: "结合最终结果、可观察执行日志与人工抽检，不索取私有思维过程。" },
          { name: "闭环能力", lookFor: "串联发现、归因、修复、回归和版本治理。" },
          { name: "评判边界", lookFor: "识别多解、评审偏差与高风险人工复核需求。" },
        ],
      },
      {
        id: "wecom-bad-case",
        category: "AI 产品设计",
        priority: 2,
        question: "讲一个你印象比较深的 Bad Case。你们最后是怎么定位的？",
        keywords: ["预期与实际", "可观察证据", "根因分层", "责任边界", "泛化修复", "回归"],
        signalGroups: {
          problem: { label: "失败定义", keywords: ["用户任务", "预期结果", "实际表现"], required: true },
          context: { label: "发生条件", keywords: ["输入特征", "能力版本", "影响范围"], required: true },
          action: { label: "定位修复", keywords: ["核验预期", "分层归因", "推动责任人"], required: true },
          evidence: { label: "诊断证据", keywords: ["执行日志", "相邻样本", "回归结果"], required: true },
          judgment: { label: "根因判断", keywords: ["知识问题", "产品规则", "能力边界"], required: true },
          reflection: { label: "泛化学习", keywords: ["机制修复", "防止补丁", "监控更新"], required: true },
        },
        followUps: [
          { id: "wecom-bad-case-f1", triggerLabel: "只描述错误结果，缺少完整发生条件", requires: ["problem", "context"], question: "当时预期是什么，实际错在了哪里？" },
          { id: "wecom-bad-case-f2", triggerLabel: "直接断言模型错误，没有核验预期与证据", requires: ["evidence", "judgment"], question: "你怎么确定是系统的问题，不是评测标准本身有问题？" },
          { id: "wecom-bad-case-f3", triggerLabel: "修复只针对单条输入打补丁", requires: ["action", "reflection"], question: "修完以后，你们怎么确认同类问题不会再出现？" },
        ],
        evaluationDimensions: [
          { name: "案例完整性", lookFor: "脱敏说明预期、实际、条件、影响与证据。" },
          { name: "根因分析", lookFor: "区分数据、知识、流程、产品规则和能力边界。" },
          { name: "责任边界", lookFor: "明确本人归因与推动动作，以及专业责任人的实现工作。" },
          { name: "泛化修复", lookFor: "覆盖相邻表达与场景，并执行完整回归。" },
        ],
      },
      {
        id: "wecom-cross-team-launch",
        category: "协作与推进",
        priority: 2,
        question: "讲一个你跨团队推进上线的项目。",
        keywords: ["共同目标", "责任人", "口径对齐", "里程碑", "范围取舍", "业务验收"],
        signalGroups: {
          problem: { label: "协作难题", keywords: ["目标冲突", "依赖阻塞", "决策缺口"], required: true },
          context: { label: "协作语境", keywords: ["参与角色", "时间资源", "约束条件"], required: true },
          action: { label: "推进动作", keywords: ["共同依据", "责任机制", "节点跟踪"], required: true },
          evidence: { label: "交付证据", keywords: ["验收样例", "风险清单", "上线结果"], required: true },
          judgment: { label: "冲突取舍", keywords: ["争议类型", "决策权", "备选方案"], required: true },
          reflection: { label: "协作复盘", keywords: ["机制不足", "后续改进", "责任边界"], required: true },
        },
        followUps: [
          { id: "wecom-cross-team-launch-f1", triggerLabel: "只说沟通和催进度", requires: ["problem", "action"], question: "这个项目最难推进的点是什么？你具体做了什么？" },
          { id: "wecom-cross-team-launch-f2", triggerLabel: "没有呈现真实冲突或决策过程", requires: ["context", "judgment"], question: "中间最大的分歧是什么？最后谁做的决定？" },
          { id: "wecom-cross-team-launch-f3", triggerLabel: "只强调按时上线，没有质量与复盘", requires: ["evidence", "reflection"], question: "如果当时确定会延期，你会怎么处理？" },
        ],
        evaluationDimensions: [
          { name: "协作结构化", lookFor: "把口头共识落成范围、责任、节点、样例和验收规则。" },
          { name: "冲突处理", lookFor: "区分争议性质，让合适的责任人做决策。" },
          { name: "项目取舍", lookFor: "能给出时间、范围和风险的明确备选方案。" },
          { name: "个人推动力", lookFor: "有本人识别阻塞、组织决策和跟踪关闭的动作。" },
        ],
      },
      {
        id: "wecom-failure-reflection",
        category: "行为与复盘",
        priority: 3,
        question: "讲一次你做错判断的经历。",
        keywords: ["本人判断", "实际影响", "根因", "机制改进", "预防措施", "迁移学习"],
        signalGroups: {
          problem: { label: "错误判断", keywords: ["本人责任", "错误假设", "关键遗漏"], required: true },
          context: { label: "影响语境", keywords: ["用户影响", "协作成本", "项目后果"], required: true },
          action: { label: "补救行动", keywords: ["及时纠偏", "影响控制", "责任沟通"], required: true },
          evidence: { label: "改进证据", keywords: ["规则变化", "流程变化", "后续验证"], required: true },
          judgment: { label: "根因认识", keywords: ["为何误判", "系统原因", "边界条件"], required: true },
          reflection: { label: "迁移学习", keywords: ["预防机制", "升级阈值", "新决策原则"], required: true },
        },
        followUps: [
          { id: "wecom-failure-reflection-f1", triggerLabel: "把问题归因于环境或他人", requires: ["problem", "judgment"], question: "当时哪个判断是你做的？为什么会判断错？" },
          { id: "wecom-failure-reflection-f2", triggerLabel: "没有说明实际影响和补救", requires: ["context", "action"], question: "造成了什么影响？你当时先做了什么？" },
          { id: "wecom-failure-reflection-f3", triggerLabel: "改进停留在更细心或多沟通", requires: ["evidence", "reflection"], question: "这件事之后，你具体改了什么做法？" },
        ],
        evaluationDimensions: [
          { name: "责任承担", lookFor: "明确本人错误，不甩锅也不替团队承担全部责任。" },
          { name: "影响具体性", lookFor: "说明真实影响，不用虚构数字放大故事。" },
          { name: "根因深度", lookFor: "从表面失误追到假设、机制或边界问题。" },
          { name: "机制改进", lookFor: "将教训转化为可执行、可验证的规则或流程。" },
        ],
      },
      {
        id: "wecom-disagreement",
        category: "行为与复盘",
        priority: 3,
        question: "讲一次你和业务、设计或者研发意见不一致的经历。",
        keywords: ["换位理解", "争议拆解", "证据收敛", "决策边界", "结果处理", "可修正性"],
        signalGroups: {
          problem: { label: "分歧核心", keywords: ["目标差异", "方案冲突", "资源矛盾"], required: true },
          context: { label: "双方立场", keywords: ["合理顾虑", "共同目标", "约束"], required: true },
          action: { label: "收敛行动", keywords: ["事实核对", "小范围验证", "备选方案"], required: true },
          evidence: { label: "决策证据", keywords: ["用户样例", "数据", "实验结果"], required: true },
          judgment: { label: "决策机制", keywords: ["争议类型", "最终责任人", "取舍理由"], required: true },
          reflection: { label: "结果复盘", keywords: ["判断修正", "相邻影响", "协作改进"], required: true },
        },
        followUps: [
          { id: "wecom-disagreement-f1", triggerLabel: "把对方描述为被说服的阻力", requires: ["problem", "context"], question: "对方当时最合理的顾虑是什么？" },
          { id: "wecom-disagreement-f2", triggerLabel: "只靠表达技巧或职位拍板", requires: ["action", "evidence"], question: "你们最后是靠什么把分歧收敛下来的？" },
          { id: "wecom-disagreement-f3", triggerLabel: "没有说明决策归属与纠错方式", requires: ["judgment", "reflection"], question: "如果后来证明你错了，你会怎么处理？" },
        ],
        evaluationDimensions: [
          { name: "换位理解", lookFor: "准确呈现不同角色的目标、约束和合理顾虑。" },
          { name: "争议拆解", lookFor: "区分事实、专业判断、方案取舍与资源优先级。" },
          { name: "证据驱动", lookFor: "用可核验信息或实验收敛，而非只靠说服。" },
          { name: "可修正性", lookFor: "证据变化后能承认错误并修正相关方案。" },
        ],
      },
    ],
  },
  {
    id: "general-ai-pm",
    title: "通用 AI 产品经理",
    description:
      "适用于通用 AI 产品岗位的精简模拟题包，覆盖问题选择、方案取舍、MVP、评测、指标、安全与跨职能协作。回答项目题时请主动脱敏，不披露可识别的个人、客户或未公开业务信息。",
    competencies: [
      "AI 机会判断",
      "AI 产品方案与 MVP",
      "质量评测与指标实验",
      "安全治理与人机协作",
      "项目所有权与跨职能协作",
    ],
    version: "1.0.0",
    questions: [
      {
        id: "general-ai-problem-selection",
        category: "AI 机会判断",
        priority: 1,
        question: "面对一个业务问题，你如何判断它是否值得用 AI 解决？",
        keywords: ["用户价值", "任务结构", "不确定性", "数据条件", "错误成本", "非 AI 基线"],
        signalGroups: {
          problem: { label: "用户问题", keywords: ["真实任务", "痛点强度", "发生频率"], required: true },
          context: { label: "可行条件", keywords: ["数据可用", "任务边界", "容错空间"], required: true },
          action: { label: "验证方法", keywords: ["人工原型", "规则基线", "小样本测试"], required: true },
          evidence: { label: "决策证据", keywords: ["质量提升", "效率收益", "用户采用"], required: true },
          judgment: { label: "方案判断", keywords: ["是否需要 AI", "能力匹配", "投入产出"], required: true },
          reflection: { label: "风险边界", keywords: ["失败后果", "人工兜底", "停止条件"], required: true },
        },
        followUps: [
          { id: "general-ai-problem-selection-f1", triggerLabel: "因为可以用 AI 就默认应该用", requires: ["problem", "judgment"], question: "什么情况下规则、搜索或流程优化会比 AI 更合适？" },
          { id: "general-ai-problem-selection-f2", triggerLabel: "只谈技术可行，缺少用户价值证据", requires: ["context", "evidence"], question: "在投入开发前，你会用什么低成本方式验证用户真的在意这个问题？" },
          { id: "general-ai-problem-selection-f3", triggerLabel: "忽略错误成本和退出条件", requires: ["action", "reflection"], question: "如果质量只能达到可用但不稳定，你如何限制场景并设置人工兜底？" },
        ],
        evaluationDimensions: [
          { name: "问题优先", lookFor: "从用户任务和价值出发，而非从模型能力反推需求。" },
          { name: "技术判断", lookFor: "比较 AI 与非 AI 基线，并说明能力适配条件。" },
          { name: "验证效率", lookFor: "先用低成本原型验证最大不确定性。" },
          { name: "风险意识", lookFor: "按错误后果限制范围并设置退出条件。" },
        ],
      },
      {
        id: "general-ai-flagship-project",
        category: "项目深挖",
        priority: 1,
        question: "请介绍一个最能代表你的 AI 产品项目，并明确你的个人贡献。",
        keywords: ["用户问题", "方案选择", "个人所有权", "质量验证", "业务结果", "复盘"],
        signalGroups: {
          problem: { label: "问题定义", keywords: ["目标用户", "核心任务", "价值假设"], required: true },
          context: { label: "项目约束", keywords: ["数据与能力", "资源", "成功标准"], required: true },
          action: { label: "个人行动", keywords: ["本人决策", "交付推进", "质量闭环"], required: true },
          evidence: { label: "结果证据", keywords: ["口径", "用户行为", "护栏表现"], required: true },
          judgment: { label: "关键取舍", keywords: ["方案比较", "范围边界", "风险权衡"], required: true },
          reflection: { label: "项目复盘", keywords: ["未达预期", "改进", "迁移方法"], required: true },
        },
        followUps: [
          { id: "general-ai-flagship-project-f1", triggerLabel: "堆叠技术名词，没有核心用户问题", requires: ["problem", "context"], question: "如果不提模型与技术名词，这个项目为谁解决了什么问题？" },
          { id: "general-ai-flagship-project-f2", triggerLabel: "个人与团队贡献边界不清", requires: ["action", "judgment"], question: "哪三个关键判断由你直接负责？哪些实现或成果不应归到你个人？" },
          { id: "general-ai-flagship-project-f3", triggerLabel: "只给结果数字，没有口径与局限", requires: ["evidence", "reflection"], question: "这些结果如何定义和验证？有哪些反例、局限或仍不能确认的因果关系？" },
        ],
        evaluationDimensions: [
          { name: "产品叙事", lookFor: "围绕用户问题、决策和结果组织项目，而非技术清单。" },
          { name: "所有权边界", lookFor: "准确区分个人判断、团队协作和专业实现。" },
          { name: "证据可信度", lookFor: "解释口径、基线、限制和未知部分。" },
          { name: "复盘深度", lookFor: "从失败和限制提炼可迁移的产品方法。" },
        ],
      },
      {
        id: "general-ai-solution-selection",
        category: "AI 方案设计",
        priority: 1,
        question: "面对同一任务，你如何在提示词、检索增强、固定工作流与自主代理之间选择方案？",
        keywords: ["任务复杂度", "知识新鲜度", "可控性", "工具调用", "成本延迟", "评测"],
        signalGroups: {
          problem: { label: "任务需求", keywords: ["输入输出", "变化程度", "成功标准"], required: true },
          context: { label: "技术约束", keywords: ["知识来源", "工具权限", "成本延迟"], required: true },
          action: { label: "选型过程", keywords: ["简单基线", "逐级增强", "原型对比"], required: true },
          evidence: { label: "方案证据", keywords: ["质量", "稳定性", "成本"], required: true },
          judgment: { label: "架构取舍", keywords: ["确定性", "自主性", "维护成本"], required: true },
          reflection: { label: "降级策略", keywords: ["失败模式", "回退", "人工接管"], required: true },
        },
        followUps: [
          { id: "general-ai-solution-selection-f1", triggerLabel: "直接选择最复杂的代理方案", requires: ["problem", "judgment"], question: "你会先建立什么最简单的基线？什么证据才值得增加自主性？" },
          { id: "general-ai-solution-selection-f2", triggerLabel: "只比较准确率，忽略系统代价", requires: ["context", "evidence"], question: "质量相近时，你如何比较时延、成本、稳定性和维护难度？" },
          { id: "general-ai-solution-selection-f3", triggerLabel: "没有失败与降级路径", requires: ["action", "reflection"], question: "检索无结果、工具失败或置信不足时，产品应该怎样降级？" },
        ],
        evaluationDimensions: [
          { name: "任务建模", lookFor: "从输入、输出、变化性和风险推导方案需求。" },
          { name: "渐进复杂度", lookFor: "从简单可测基线开始，用证据增加复杂度。" },
          { name: "系统权衡", lookFor: "综合质量、时延、成本、稳定性和维护性。" },
          { name: "可靠性设计", lookFor: "为关键失败模式准备降级和人工接管。" },
        ],
      },
      {
        id: "general-ai-mvp",
        category: "AI 方案设计",
        priority: 1,
        question: "你会如何定义一个 AI 产品的 MVP，使它既能验证价值又不掩盖质量风险？",
        keywords: ["最大不确定性", "窄任务", "人工服务", "能力边界", "质量门槛", "扩展条件"],
        signalGroups: {
          problem: { label: "验证问题", keywords: ["最大不确定性", "用户任务", "价值假设"], required: true },
          context: { label: "MVP 条件", keywords: ["目标用户", "数据范围", "风险等级"], required: true },
          action: { label: "最小方案", keywords: ["窄场景", "人工兜底", "可观察流程"], required: true },
          evidence: { label: "验证标准", keywords: ["任务成功", "质量门槛", "重复使用"], required: true },
          judgment: { label: "范围边界", keywords: ["主动不做", "发布限制", "扩展条件"], required: true },
          reflection: { label: "失败学习", keywords: ["退出条件", "坏样本", "假设更新"], required: true },
        },
        followUps: [
          { id: "general-ai-mvp-f1", triggerLabel: "MVP 是缩小版功能清单，没有验证目标", requires: ["problem", "evidence"], question: "这个 MVP 最需要回答哪一个问题？你如何在短周期内获得可信证据？" },
          { id: "general-ai-mvp-f2", triggerLabel: "没有明确用户、数据和能力边界", requires: ["context", "judgment"], question: "一期支持哪些输入与任务，明确不支持什么，用户如何感知边界？" },
          { id: "general-ai-mvp-f3", triggerLabel: "用人工兜底隐藏产品质量问题", requires: ["action", "reflection"], question: "人工参与如何被记录和计入成本，避免形成虚假的自动化效果？" },
        ],
        evaluationDimensions: [
          { name: "验证聚焦", lookFor: "围绕最大不确定性而非完整愿景定义 MVP。" },
          { name: "边界透明", lookFor: "明确支持范围、失败方式和用户预期。" },
          { name: "真实成本", lookFor: "将人工兜底、运营和修复成本纳入验证。" },
          { name: "扩展纪律", lookFor: "用明确证据决定继续、扩展或停止。" },
        ],
      },
      {
        id: "general-ai-evaluation",
        category: "评测与迭代",
        priority: 1,
        question: "你会如何搭建 AI 产品的离线评测、线上监控与坏样本迭代闭环？",
        keywords: ["任务分层", "评测集", "离线指标", "线上行为", "坏样本归因", "回归"],
        signalGroups: {
          problem: { label: "质量定义", keywords: ["任务成功", "关键错误", "用户后果"], required: true },
          context: { label: "样本覆盖", keywords: ["真实分布", "长尾边界", "高风险样本"], required: true },
          action: { label: "评测流程", keywords: ["离线门禁", "线上监控", "归因回归"], required: true },
          evidence: { label: "评判证据", keywords: ["可核验预期", "行为指标", "人工复核"], required: true },
          judgment: { label: "指标取舍", keywords: ["总体分数", "分层指标", "发布阈值"], required: true },
          reflection: { label: "评测维护", keywords: ["数据漂移", "污染防范", "版本治理"], required: true },
        },
        followUps: [
          { id: "general-ai-evaluation-f1", triggerLabel: "用单一准确率代表全部质量", requires: ["problem", "judgment"], question: "哪些错误虽然少见但必须单独设门槛？为什么平均分会掩盖它们？" },
          { id: "general-ai-evaluation-f2", triggerLabel: "评测集只有常规样本或静态样本", requires: ["context", "reflection"], question: "如何覆盖边界与高风险样本，并防止评测集过期或被针对性优化？" },
          { id: "general-ai-evaluation-f3", triggerLabel: "离线、线上和迭代彼此割裂", requires: ["action", "evidence"], question: "一个线上坏样本怎样进入归因、修复、回归和新版本发布门禁？" },
        ],
        evaluationDimensions: [
          { name: "质量建模", lookFor: "将任务成功、关键错误和用户后果转成分层标准。" },
          { name: "样本策略", lookFor: "兼顾真实分布、边界、长尾与高风险场景。" },
          { name: "端到端闭环", lookFor: "连接离线评测、线上监控、人工复核与回归。" },
          { name: "持续治理", lookFor: "管理评测版本、漂移与针对测试集过拟合的风险。" },
        ],
      },
      {
        id: "general-ai-metrics-experiment",
        category: "指标与实验",
        priority: 2,
        question: "你会如何证明一项 AI 功能改善了用户结果，而不只是提高了调用量？",
        keywords: ["任务结果", "质量指标", "行为链路", "对照实验", "选择偏差", "护栏"],
        signalGroups: {
          problem: { label: "价值假设", keywords: ["用户任务", "原流程问题", "目标结果"], required: true },
          context: { label: "实验语境", keywords: ["用户分层", "任务频率", "学习效应"], required: true },
          action: { label: "实验设计", keywords: ["随机对照", "分阶段开放", "前后比较"], required: true },
          evidence: { label: "指标链路", keywords: ["任务完成", "返工", "持续采用"], required: true },
          judgment: { label: "因果判断", keywords: ["替代解释", "新奇效应", "样本偏差"], required: true },
          reflection: { label: "风险护栏", keywords: ["严重错误", "投诉", "成本延迟"], required: true },
        },
        followUps: [
          { id: "general-ai-metrics-experiment-f1", triggerLabel: "只有使用次数或满意度", requires: ["problem", "evidence"], question: "请把指标从一次调用延伸到任务完成、返工和后续行为。" },
          { id: "general-ai-metrics-experiment-f2", triggerLabel: "默认使用者表现好就是功能有效", requires: ["context", "judgment"], question: "主动使用者本来就更熟练时，你如何降低选择偏差？" },
          { id: "general-ai-metrics-experiment-f3", triggerLabel: "只看收益，缺少质量与成本护栏", requires: ["action", "reflection"], question: "什么质量、安全、时延或成本变化会让你停止实验？" },
        ],
        evaluationDimensions: [
          { name: "指标链路", lookFor: "从调用延伸到质量、任务结果和持续采用。" },
          { name: "实验设计", lookFor: "根据条件选择对照、分阶段或准实验方法。" },
          { name: "因果意识", lookFor: "识别选择偏差、新奇效应和外部变化。" },
          { name: "风险收益", lookFor: "同步观察严重错误、投诉、时延和成本。" },
        ],
      },
      {
        id: "general-ai-safety",
        category: "安全与治理",
        priority: 1,
        question: "设计一个会读取业务数据并调用工具的 AI 产品时，你会建立哪些安全与治理机制？",
        keywords: ["最小权限", "数据隔离", "提示注入", "工具白名单", "人工确认", "审计回滚"],
        signalGroups: {
          problem: { label: "威胁识别", keywords: ["数据泄露", "恶意输入", "错误动作"], required: true },
          context: { label: "风险语境", keywords: ["数据敏感度", "动作可逆性", "影响范围"], required: true },
          action: { label: "防护机制", keywords: ["最小授权", "输入隔离", "执行前校验"], required: true },
          evidence: { label: "安全证据", keywords: ["对抗测试", "审计日志", "事件监控"], required: true },
          judgment: { label: "风险分级", keywords: ["自动执行", "人工确认", "禁止动作"], required: true },
          reflection: { label: "事件响应", keywords: ["撤销回滚", "影响追踪", "策略更新"], required: true },
        },
        followUps: [
          { id: "general-ai-safety-f1", triggerLabel: "只提内容审核，忽略权限和工具风险", requires: ["problem", "context"], question: "读取数据、生成内容和执行动作分别有哪些不同风险？" },
          { id: "general-ai-safety-f2", triggerLabel: "用一次性确认替代持续权限校验", requires: ["action", "judgment"], question: "工具每次执行前应重新检查什么？哪些动作即使授权也不应自动执行？" },
          { id: "general-ai-safety-f3", triggerLabel: "没有测试、审计和事故恢复", requires: ["evidence", "reflection"], question: "上线前怎样对抗测试？出错后如何确定影响范围、撤销动作并更新防护？" },
        ],
        evaluationDimensions: [
          { name: "威胁模型", lookFor: "覆盖泄露、注入、越权、误操作和间接推断。" },
          { name: "分层防护", lookFor: "在数据、指令、工具与输出各层设置控制。" },
          { name: "风险分级", lookFor: "按敏感度、可逆性和影响范围决定自动化程度。" },
          { name: "可恢复性", lookFor: "具备测试、监控、审计、撤销和事件复盘机制。" },
        ],
      },
      {
        id: "general-ai-collaboration",
        category: "协作与复盘",
        priority: 2,
        question: "当业务希望尽快上线、算法认为质量不足、工程担心稳定性时，你会如何推动决策？",
        keywords: ["共同目标", "争议拆解", "证据缺口", "风险分层", "灰度方案", "决策责任"],
        signalGroups: {
          problem: { label: "冲突定义", keywords: ["价值速度", "质量门槛", "稳定性风险"], required: true },
          context: { label: "各方约束", keywords: ["业务窗口", "样本证据", "工程能力"], required: true },
          action: { label: "推进方案", keywords: ["共同指标", "灰度范围", "应急预案"], required: true },
          evidence: { label: "决策证据", keywords: ["质量分层", "压测", "用户验证"], required: true },
          judgment: { label: "责任与取舍", keywords: ["不可妥协底线", "风险接受者", "最终决策人"], required: true },
          reflection: { label: "复盘机制", keywords: ["上线门禁", "监控阈值", "流程改进"], required: true },
        },
        followUps: [
          { id: "general-ai-collaboration-f1", triggerLabel: "把冲突归结为沟通不充分", requires: ["problem", "context"], question: "三方各自掌握什么事实、承担什么风险，还缺少哪项关键证据？" },
          { id: "general-ai-collaboration-f2", triggerLabel: "只给全量上线或完全延期两个选择", requires: ["action", "evidence"], question: "能否通过收窄用户、任务或动作权限设计一个可控的灰度方案？" },
          { id: "general-ai-collaboration-f3", triggerLabel: "没有底线、决策归属和复盘", requires: ["judgment", "reflection"], question: "哪些底线不可妥协，谁接受剩余风险，什么信号会触发回滚？" },
        ],
        evaluationDimensions: [
          { name: "冲突拆解", lookFor: "区分价值、质量、稳定性和资源问题。" },
          { name: "证据组织", lookFor: "明确已知、未知和获得关键证据的最短路径。" },
          { name: "方案能力", lookFor: "通过范围、权限、灰度和预案平衡速度与风险。" },
          { name: "决策治理", lookFor: "明确底线、风险接受者、最终责任人和回滚条件。" },
        ],
      },
    ],
  },
];

if (typeof window !== "undefined") {
  window.MOCK_QUESTION_PACKS = MOCK_QUESTION_PACKS;
}

if (typeof module !== "undefined" && module.exports) {
  module.exports = MOCK_QUESTION_PACKS;
}
